### ISSUE TITLE
Criar páginas de produtos no site do Felicilab

### ISSUE THREAD

**Issue by danielgula** [EscolaDeSaudePublica/sus.ce.gov.br#106]
## **Objetivo**

**Como** internauta
**Quero** conhecer os produtos do Felicilab
**Para** ver a inovação aberta em saúde da ESP

## **Contexto**

Para a nova versão do site, colocaremos os principais produtos que temos, principalmente por causa do prêmio ENAP.

## **Escopo**

- [x] Criar página do iSUS.
- [x] Criar página do Mapas.
- [x] Criar página do RPES.
- [x] Criar página da IdSaúde.
- [x] Criar página do Qualiquiz.
- [x] Criar página do Sagu.
- [x] Página das soluções

## **Critérios de Aceitação**

**Dado que** estou na Internet
**Quando** entro no link [Nossas Soluções]
**então** vejo os produtos do Felicilab

**Comment by danielgula** [comment]
@Clarisse1983 @uira  teria como validar com o tático que produtos entrariam para essa versão de lançamento? Na descrição da issue tem algumas sugestões.

**Comment by uira** [comment]
@danielgula iSUS
Mapas
IDSaúde
QualiQuiz
Sagu
RPES

**Comment by saracafe** [comment]
Atualizando: https://docs.google.com/document/d/1IGCe-kQh5ZpBSmG_licV1UHkyv0HbsWnd0r_KkWnjno/edit?usp=sharing

**Comment by ClarisCaval** [comment]
Para usar como base:
- RPES:
https://docs.google.com/document/d/1C-pcFOC-BQJK0rWhbf1C6OXzzktbACSyew9-grBjVvE/edit
- Qualiquiz:
https://docs.google.com/presentation/d/1QJI8a35IYsHdDMyns4TjWSRiVFSQOCjVKImxTNWHAZg/edit#slide=id.gaeff06fe0a_0_42

**Comment by danielgula** [comment]
Foi criada a página de soluções e todas as páginas filhas com textos e links. A página de soluções está acessível mas faltam conteúdos. Segue link:

https://sus.ce.gov.br/felicilab/solucoes/

**Comment by danielgula** [comment]
Foi feito um ajuste em todos os templastes para ficar parecido com o layout das páginas e do background, para que a experiência de navegação integre melhor a estética do site original.

**Comment by danielgula** [comment]
Atualização feita para o produto RPES. O card pode ser fechado.

**Comment by danielgula** [comment]
Foi feito um ajuste na experiência mobile de todos os produtos e seus templates.
