### ISSUE TITLE
Revisar perfis das pessoas DIT/FeliciLab para site

### ISSUE THREAD

**Issue by saracafe** [EscolaDeSaudePublica/sus.ce.gov.br#107]
## **Objetivo**

**Como** pessoa comunicadora da inovação  
**Quero** publicar o perfil da pessoas  
**Para** ter um espaço para colaboradores no site

## **Contexto**

Pessoas já saíram e novos colaboradores já entraram nos times dos projetos/produtos. É preciso revisar e atualizar o documento de perfil das novas pessoas integrantes para ser colocado no site. 

## **PubliciLab**

- [x] Deslocar pessoas que saíram para memória histórica no docs
- [x] Atualizar os perfis de quem está ativo no docs
- [x] Falar com as pessoas novatas para preencherem o forms
- [x] Inserir os novos perfis no doc

## **Critérios de Aceitação**

- [x] Perfis criados 
**Dado que** sou pessoa comunicadora da inovação
**Quando** atualizo o perfil das pessoas
**então** colocar um espaço para colaboradores no site

- [x] Páginas criadas
**Dado que** sou internauta
**Quando** acesso o link [Pessoas] no site felicilab
**então** vejo todos os colaboradores do time

## Observações
https://docs.google.com/document/d/1TOuIFa7Ds1cOlgOmvkFQIIt2Jgnl2m2abn1VJUil1F4/edit?usp=sharing

**Comment by saracafe** [comment]
Atualizando os perfis e falando com os novatos: https://docs.google.com/document/d/1TOuIFa7Ds1cOlgOmvkFQIIt2Jgnl2m2abn1VJUil1F4/edit?usp=sharing

**Comment by raiannyqz** [comment]
Os Perfis foram criados no wordpress de acordo com o que eles responderam pelo GoogleForms e que @saracafe editou.
Os perfis foram: Lucas Tandy, Aislan Freitas, Pedro Victor, Bruna Queiroz, Paulo Rafael, Janete Amaral, Thais Toscano, Daiane Abreu, Talita Macedo, Raianny Queiroz, Washington Forte, Wanderley Lima, Victor Magalhães, Uirá Porã, Susi, Sara Café, Samara de Almeida Mesquita, Rodrigo Silvestre, RaniGub, Paulo Amoreira, Mayara Monte, Marcus Rodrigues, Marcos Oliveira, Luanna Araújo, Kelma Souto, Junior Oliveira, Jéferson, Jacson Passold, Helen Hilário, Genilton, Gabriela Marques, Flavianne, Fernanda, Ericson Moreira, Clarisse Castro, Clarissa Gomes, Camila Colares, Ana Paula Vieira, Alê, Rodolpho, Alex, Daniel Gularte.
Para conferir e fazer a revisão dos perfis foi criado uma página fake que não está publicada, link:
https://sus.ce.gov.br/felicilab/?page_id=1674&preview=true

**Comment by raiannyqz** [comment]
@danielgula Daniel o perfil do Aislan Freitas continua dando erro, aparecendo só a foto, teria como olhar o que tá acontecendo? Porque eu já apaguei e criei de novo esse perfil e o problema persiste! 
https://sus.ce.gov.br/felicilab/?page_id=1674&preview=true

**Comment by ClarisCaval** [comment]
@danielgula fará uma revisão de uma única inconsistência hoje ;)

**Comment by danielgula** [comment]
> @danielgula fará uma revisão de uma única inconsistência hoje ;)

Revisão feita e bug corrigido. Pode fechar esse card.

**Comment by raiannyqz** [comment]
Com a finalidade de organização de tarefas o card foi criado: Criar perfis das pessoas DIT/FeliciLab para site
https://github.com/EscolaDeSaudePublica/sus.ce.gov.br/issues/111

**Comment by ClarisCaval** [comment]
@saracafe vai realizar pequenas alterações indicadas no documento
https://docs.google.com/document/d/1TOuIFa7Ds1cOlgOmvkFQIIt2Jgnl2m2abn1VJUil1F4/edit#heading=h.cnqyatfslyvk

**Comment by danielgula** [comment]
Foi feito um ajuste de performance nos perfis, padronizando os fundos de tela e as imagens destacadas para se tornar mais dinâmica a atualização.
Como todos os perfis pretendidos foram publicados, acordamos um fluxo por email para a manutenção desses conteúdos, a partir do recebimento do email e organização feita pela @raiannyqz 
Assim sendo, esse card está concluído.
