### ISSUE TITLE
Refinamento - Site Residência

### ISSUE THREAD

**Issue by raiannyqz** [EscolaDeSaudePublica/sus.ce.gov.br#108]
## **Objetivo**

**Como** Residentes e possíveis ingressantes a residentes
**Quero** precisam obter informações, ter interação e comunicação
**Para** se relacionar com o programa da residência.

## **Contexto**

- Os residentes precisam de um site para melhorar o relacionamento com o programa da Residência Multiprofissional e este, por sua vez, requer uma melhor visibilidade do seu conteúdo informativo.
- Os possíveis ingressantes precisam obter informações a cerca do programa, dos editais, bem como indicativos e outros assuntos que possa interessar a sua participação.
- Neste sentido, devemos criar um site que possa habilitar essa interação do residente e possíveis ingressantes para com o programa servindo como canal informativo e de comunicação.

## **Escopo**

- [x] Pontos textuais para a elaboração das páginas do site
- [x] Planejar qual o conteúdo para as páginas do Site
- [x] Elaboração de questionário e/ou atividade com residentes e possíveis residentes
- [x] Entrevista 1 com possível ingressante à residente 
- [x] Rever AI a partir das colocações realizadas em entrevista 1.
- [ ] Entrevista 2  com residente
- [ ] Rever AI a partir das colocações realizadas em entrevista 2.
- [x] Criar Página Notícia
- [x] Criar Página Sobre a ESP

## **Critérios de Aceitação**

- [x] titulo  
**Dado que** ao abrir o site da residência
**Quando** seja possível obter informações sobre o programa e uma comunicação com este
**então** resultando no engajamento e comunicação do residente.

## Observações
https://www.figma.com/file/sBF9hDgBsIM5IXJHQwrUOS/Arquitetura-da-Informa%C3%A7%C3%A3o
https://www.figma.com/file/fLpsySTOeWNzOiB2Bx97yD/Design-Arquitetura?node-id=0%3A1
https://www.figma.com/proto/VuN7wHJhnW2taJwdgRrhGg/Arquitetura?node-id=38%3A295&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=38%3A295
https://www.figma.com/file/e4wZgbXP3Tpo4hqn2SPOEO/Elabora%C3%A7%C3%A3o-de-question%C3%A1rio-e%2Fou-atividade-com-poss%C3%ADveis-residentes?node-id=0%3A1
https://sus.ce.gov.br/residenciasespce/

**Comment by raiannyqz** [comment]
Pontos textuais para a elaboração das páginas do site, estes pontos foram repassados para a DIPSA, eles são essenciais para elaborar os dados textuais a serem inseridos nas páginas.
<img width="433" alt="02" src="https://user-images.githubusercontent.com/28989404/138926157-e67879e7-be71-4919-a3e0-de482c884214.png">

**Comment by raiannyqz** [comment]
Elaboração de questionário e/ou atividade com residentes e possíveis residentes:
https://www.figma.com/file/e4wZgbXP3Tpo4hqn2SPOEO/Elabora%C3%A7%C3%A3o-de-question%C3%A1rio-e%2Fou-atividade-com-poss%C3%ADveis-residentes?node-id=0%3A1

**Comment by raiannyqz** [comment]
Ontem conversei com uma possível residente sobre pontos que para elapossa ser importantes na cosntrução do site, foi um momento super esclarecedor, para isso fiz uma dinamica quw conta no link: https://www.figma.com/file/e4wZgbXP3Tpo4hqn2SPOEO/Elabora%C3%A7%C3%A3o-de-question%C3%A1rio-e%2Fou-atividade-com-poss%C3%ADveis-residentes?node-id=0%3A1
Esta mesma dinâmica será aplicada amanhã com um residente que Diego me indicou.

**Comment by raiannyqz** [comment]
@RaniGub  como próximo passo precisarei de alguns dados e textos para compor as paginas, pontuei alguns deles para enviar para a Dipsa e outros precisarei entender melhor como proceder. Uma delas é com relação ao editais, provas e gabaritos (consta no site do ares https://www.resmedceara.ufc.br/ares/processo-seletivo
Eles querem colocar o que tá no site do ares numa pagina da residencia, no caso o que faço ? Baixo todos os arquivos pra carregar no site, faço esse trabalho inicial e depois registro um editor para que fique reponsável pelos proximos editais que irão abrir?
A outra questão é sobre: Ascon precisa aprovar a página de noticias  e Após aprovação - cadastrar um editor para que ele fique fazendo essas futuras publicações?

**Comment by RaniGub** [comment]
> @RaniGub  como próximo passo precisarei de alguns dados e textos para compor as paginas, pontuei alguns deles para enviar para a Dipsa e outros precisarei entender melhor como proceder. Uma delas é com relação ao editais, provas e gabaritos (consta no site do ares https://www.resmedceara.ufc.br/ares/processo-seletivo
> Eles querem colocar o que tá no site do ares numa pagina da residencia, no caso o que faço ? Baixo todos os arquivos pra carregar no site, faço esse trabalho inicial e depois registro um editor para que fique reponsável pelos proximos editais que irão abrir?
> A outra questão é sobre: Ascon precisa aprovar a página de noticias  e Após aprovação - cadastrar um editor para que ele fique fazendo essas futuras publicações?

Oi Raianny, marquei na agenda um momento com vc amanhã. Se der tempo a gente refina e vejo se consigo lhe ajudar.

**Comment by raiannyqz** [comment]
Olá aguardo contato com o residente para entrevistá-lo, Diego que está intermediando. 
Aguardo conteúdo que pedi pra DIPSA para inserir nas páginas.

**Comment by raiannyqz** [comment]
@RaniGub  e @uira Bom dia: algumas das atividades eu não pude finalizar, pois eu precisava que a DIPSA me enviasse alguns pontos textuais que pedi para o conteúdo do site, contudo não foi possível. 
Também não foi possivel marcar com o residente, tendo isso em vista pensei em outra metodologia para obter estes dados: formulário Docs e enviar para a Dipsa e também para o residente, para que ele possa responder no tempo que ele puder, sem precisar marcar uma reunião.
Hoje pela manhã farei mais uns ajustes na AI e no site no wordpress. 
E a partir disso podemos marcar um pareamento para mostrar o resultado até hoje?

**Comment by RaniGub** [comment]
Bom dia @raiannyqz, não acho que o formulário seja o caminho mais adequado, pois podem aparecer sombreamentos que só serão observados após as respostas. Fora que os produtos devem seguir um cronograma de entrega, as informações são importantes ao ponto de bloquear o Site? Se não forem, sugiro que continue o desenvolvimento e reforce o papo com eles em outro momento. Falei com o @pauloamoreira agora a pouco ele vai refinar com você a problematização e AI do site, seguindo o fluxo proposto de coparticipação do DesignLab.

**Comment by raiannyqz** [comment]
> Bom dia @raiannyqz, não acho que o formulário seja o caminho mais adequado, pois podem aparecer sombreamentos que só serão observados após as respostas. Fora que os produtos devem seguir um cronograma de entrega, as informações são importantes ao ponto de bloquear o Site? Se não forem, sugiro que continue o desenvolvimento e reforce o papo com eles em outro momento. Falei com o @pauloamoreira agora a pouco ele vai refinar com você a problematização e AI do site, seguindo o fluxo proposto de coparticipação do DesignLab.

@RaniGub Pois é, o bom mesmo é falar diretamente. Pois tá certo vou ver com Paulo sobre isso. Agradeço!

**Comment by raiannyqz** [comment]
Retirei algumas tarefas que dependem da resposta de outras pessoas para que eu possa finalizar esta issue de acordo com as tarefas que foram cumpridas, que não estavam na dependência de outras pessoas.

**Comment by raiannyqz** [comment]
Sobre a reunião com o residente, estou vendo com outro, aguardo a sua disponibilidade de dia e horário.

**Comment by raiannyqz** [comment]
Link da AI: https://www.figma.com/file/sBF9hDgBsIM5IXJHQwrUOS/Arquitetura-da-Informa%C3%A7%C3%A3o?node-id=121%3A442
Link do site da residência: https://sus.ce.gov.br/residenciasespce/

**Comment by pauloamoreira** [comment]
> Bom dia @raiannyqz, não acho que o formulário seja o caminho mais adequado, pois podem aparecer sombreamentos que só serão observados após as respostas. Fora que os produtos devem seguir um cronograma de entrega, as informações são importantes ao ponto de bloquear o Site? Se não forem, sugiro que continue o desenvolvimento e reforce o papo com eles em outro momento. Falei com o @pauloamoreira agora a pouco ele vai refinar com você a problematização e AI do site, seguindo o fluxo proposto de coparticipação do DesignLab.

.em reunião com @raiannyqz , acordamos que ela irá viabilizar a produção de alguns materiais estruturantes necessários para fazer uma nova proposição de AI do site, entre os quais: inception, mapeamento de conteúdos (quais anseios serão respondidos pelo site) e a jornada as pessoas usuárias através destes conteúdos. quando essa nova proposição de AI estiver pronta, podemos voltar a parear.

**Comment by raiannyqz** [comment]
> > Bom dia @raiannyqz, não acho que o formulário seja o caminho mais adequado, pois podem aparecer sombreamentos que só serão observados após as respostas. Fora que os produtos devem seguir um cronograma de entrega, as informações são importantes ao ponto de bloquear o Site? Se não forem, sugiro que continue o desenvolvimento e reforce o papo com eles em outro momento. Falei com o @pauloamoreira agora a pouco ele vai refinar com você a problematização e AI do site, seguindo o fluxo proposto de coparticipação do DesignLab.
> 
> .em reunião com @raiannyqz , acordamos que ela irá viabilizar a produção de alguns materiais estruturantes necessários para fazer uma nova proposição de AI do site, entre os quais: inception, mapeamento de conteúdos (quais anseios serão respondidos pelo site) e a jornada as pessoas usuárias através destes conteúdos. quando essa nova proposição de AI estiver pronta, podemos voltar a parear.

Ótimo!!!! Muito obrigada!!

**Comment by raiannyqz** [comment]
Sobre os conteúdos foi criado outro issue: https://github.com/escoladesaudepublica/sus.ce.gov.br/issues/110 Para concentrar e relatar melhor as atividades relacionadas a esta atividade, dividindo as tarefas.

**Comment by raiannyqz** [comment]
Sobre o 2 º  residente eu tou em contato com duas pessoas, residentes da ESP, uma delas, na segunda-feira dia 8 de novembro, me disse que estaria ocupada esta semana, mas que veria com os colegas. 
<img width="380" alt="Captura de tela 2021-11-10 102430" src="https://user-images.githubusercontent.com/28989404/141124952-ea6f7b4e-1702-4c2a-9d2e-f5de3621b9b6.png">
Hoje dia 10 de novembro 2021, voltei a comentar e aguardo o retorno:
<img width="601" alt="2" src="https://user-images.githubusercontent.com/28989404/141126503-b9fadcd0-1e30-4cc6-b7bd-0f2f2e648b5f.png">


A outra pessoa que estu contactando está intermediando, a procura de alguém que possa ter um tempo a disponibilizar .
<img width="598" alt="3" src="https://user-images.githubusercontent.com/28989404/141126468-590e5f66-1226-4866-92c0-2e161e09370e.png">

**Comment by raiannyqz** [comment]
Sobre o 2 º residente eu tou em contato com duas pessoas, residentes da ESP, uma delas, na segunda-feira dia 8 de novembro, me disse que estaria ocupada esta semana, mas que veria com os colegas.
<img width="568" alt="1" src="https://user-images.githubusercontent.com/28989404/141127421-5f8e132d-122e-4698-82bc-3ebd2ff3569c.png">

Hoje dia 10 de novembro 2021, voltei a comentar e aguardo o retorno:

<img width="601" alt="2" src="https://user-images.githubusercontent.com/28989404/141127493-28c8d068-f94a-47b2-b6f6-2612d5bf315a.png">

A outra pessoa que estou contactando está intermediando, a procura de alguém que possa ter um tempo a disponibilizar 
<img width="598" alt="3" src="https://user-images.githubusercontent.com/28989404/141127537-0fe23857-fd5b-40b8-9b54-3d1f064840e5.png">
.

**Comment by raiannyqz** [comment]
Neste card não foi possivel realizar a tarefa de conversar com um residente. Finalizo aqui a contribuição neste card que aguarda continuidade para o próximo bolsista, mediante suas alterações e metodologias. @uira @RaniGub

**Comment by danielgula** [comment]
Iremos retomar essa atividade com um novo refinamento para a construção de uma página que atenda às necessidades emergenciais da área.

**Comment by RaniGub** [comment]
Essa tarefa, assim como as anteriores, serão consideradas e passarão por uma análise do Jorge para que possamos dar continuidade.
