### ISSUE TITLE
Criar arquitetura do site Felicilab 2.0

### ISSUE THREAD

**Issue by danielgula** [EscolaDeSaudePublica/sus.ce.gov.br#109]
## **Objetivo**

**Como** designer
**Quero** montar a AI do site do Felicilab
**Para** construir a melhore experiência do usuário

## **Contexto**

Com as entregas da estrutura de dados pelo @wforte88 e os conteúdos atualmente publicados pelo Publicilab, faz-se necessário um estudo da AI do site do Felicilab para sua primeira entrega, trabalhando com produtos e pessoas, já desenhando pontes para falar sobre a inovação da escola na dimensão do laboratório. O foco será emergencialmente publicizar o que fazemos e quem somos.

## **Escopo**

- [x] Desenhar perguntas iniciais para inceptions
- [x] Construir estrutura de dados
- [x] Construir menu do site
- [x] Revisão da AI (Designlab)

## **Fora de Escopo**

Não será feito no momento o trabalho de relacionamento com a política de inovação e suas personas.

## **Critérios de Aceitação**

**Dado que** sou designer
**Quando** acesso o projeto do site Felicilab no Figma
**então** Vejo a arquitetura para o site se construído

**Comment by danielgula** [comment]
@RaniGub quando você tem um tempo pra gente revisar a AI do site do Felicilab? 30 minutos são suficientes.

**Comment by RaniGub** [comment]
> @RaniGub quando você tem um tempo pra gente revisar a AI do site do Felicilab? 30 minutos são suficientes.
Vou criar um card da revisão, marquei o pareamento para amanhã (27/10) 15h.

**Comment by RaniGub** [comment]
Foi adicionada a dependência na issue do DesignLab #156 para que a Arquitetura possa ser reavaliada.

**Comment by danielgula** [comment]
Acordado com o Designlab uma versão emergencial para o Prêmio ENAP. A partir daí será feita inception para o novo site.

**Comment by danielgula** [comment]
Como esta versão da AI está no ar, essa demanda será fechada. Uma nova versão do site (2.5 ou 3.0) será pensada em novo movimento da equipe. Card será fechado.
