### ISSUE TITLE
Criar perfis das pessoas DIT/FeliciLab para site

### ISSUE THREAD

**Issue by raiannyqz** [EscolaDeSaudePublica/sus.ce.gov.br#111]
## **Objetivo**

**Como** pessoa do design e da inovação
**Quero** criar e publicar o perfil das pessoas
**Para** ter um espaço para colaboradores no site

## **Contexto**

- Diante da entrada e saída de colaboradores é preciso revisar quem está no time e atualizar o perfil dos integrantes para ser criado os perfis no site, associando projetos aos produtos. Para isso, foi realizado um formulário, na qual 46 pessoas responderam e outras ainda irão responder.

## **Escopo**

- [x] Criação dos perfis: Laysa, Nicolas Linhares, Lucas Tandy, Aislan Freitas, Pedro Victor, Bruna Queiroz, Paulo Rafael, Janete Amaral, Thais Toscano, Daiane Abreu, Talita Macedo, Raianny Queiroz, Washington Forte, Wanderley Lima, Victor Magalhães, Uirá Porã, Susi, Sara Café, Samara de Almeida Mesquita, Rodrigo Silvestre, RaniGub, Paulo Amoreira, Mayara Monte, Marcus Rodrigues, Marcos Oliveira, Luanna Araújo, Kelma Souto, Junior Oliveira, Jéferson, Jacson Passold, Helen Hilário, Genilton, Gabriela Marques, Flavianne, Fernanda, Ericson Moreira, Clarisse Castro, Clarissa Gomes, Camila Colares, Ana Paula Vieira, Alexandre, Rodolpho, Alex, Daniel Gularte. Ao todo 46 Perfis .
- [x] Revisão do perfis criados

## **Fora de Escopo**

- Linkar o perfis criados aos produtos, até então!

## **Critérios de Aceitação**

- [x] titulo  
**Dado que** sou pessoa do design e inovação
**Quando** crio o perfil das pessoas 
**então** crio um espaço para colaboradores no site

## Observações
https://sus.ce.gov.br/felicilab/?page_id=1674&preview=true

**Comment by raiannyqz** [comment]
@danielgula se tiver algo que possa ser acrescentado nesta issue, por favor comentar.

**Comment by danielgula** [comment]
Já podemos fechar essa demanda, que foi concluída.
