### ISSUE TITLE
Site da Residência - Inception

### ISSUE THREAD

**Issue by raiannyqz** [EscolaDeSaudePublica/sus.ce.gov.br#112]
## **Objetivo**

**Como** pessoa do design e da inovação
**Quero** alinhar as ideias e dados coletados sobre o produto mínimo viável 
**Para** ser construído.

## **Contexto**

- Foi criado a Ai e o design do site da residencia da ESP com objetivo inicial de atender aos residente e possíveis residentes e percebemos a necessidade de retroceder algumas etapas para validar esta Ai através da inception. Afim de atender melhor esta demanda.

## **Escopo**

- [x] VISÃO DO PRODUTO /FUNCIONALIDADE
- [x] É - NÃO É - FAZ - NÃO FAZ 
- [x] PERSONAS
- [x] JORNADA DA PESSOA USUÁRIA
- [x] OBJETIVOS DO PRODUTO/FUNCIONALIDADE
- [x] BRAINSTORM DE FUNCIONALIDADES

## **Critérios de Aceitação**

- [x] titulo  
**Dado que** sou pessoa do design e inovação
**Quando** faço a inception
**então** melhoro o resultado da Ai.

## Observações
https://www.figma.com/file/WSBy21DCXM72v9MdZa025V/Inception-Site-Resid%C3%AAncia?node-id=0%3A1

**Comment by RaniGub** [comment]
Olá @pauloamoreira , você participou desse momento?

**Comment by RaniGub** [comment]
Bom dia gente, retirei a marcação do Paulo pois ele não participou do momento.

**Comment by raiannyqz** [comment]
@RaniGub realizarei a inception hoje com a Barbara e o Diego ás 10:00 hs. A dr Olivia não poderá participar, por questões pessoais.

**Comment by raiannyqz** [comment]
@danielgula você poderá participar da reunião com a Dipsa hoje as 10:00 hs?

**Comment by raiannyqz** [comment]
Hoje foi realizado a inception com a Dipsa e participação de @pauloamoreira , ficou acordado de darmos continuidade na pr[oxima quinta-feira dia 18 às 10:00hs.

**Comment by RaniGub** [comment]
Olá @raiannyqz já criei um card para que o Paulo possa apoiar o processo pelo DesignLab # 166, vou retornar essa tarefa para o 'Tudão' em nosso workspace.

**Comment by raiannyqz** [comment]
> Olá @raiannyqz já criei um card para que o Paulo possa apoiar o processo pelo DesignLab # 166, vou retornar essa tarefa para o 'Tudão' em nosso workspace.

Ah tá certo, entendido! Obrigada!

**Comment by RaniGub** [comment]
Bom dia @raiannyqz . Quando concluir a consolidação da Inception aproxime o @pauloamoreira para revisão da AI.

**Comment by raiannyqz** [comment]
> Bom dia @raiannyqz . Quando concluir a consolidação da Inception aproxime o @pauloamoreira para revisão da AI.

Sim acredito que hoje eu termine essa parte, apartir de amanhã já posso marcar com @pauloamoreira , pode me dizer quando é possível pra ti @pauloamoreira ?

**Comment by pauloamoreira** [comment]
@raiannyqz podemos parear na segunda, dia 29/11, as 14h, se você estiver disponível.

**Comment by RaniGub** [comment]
@pauloamoreira participou da Inception e fará a consolidação em texto descritivo. Após isso, irá parear com @danielgula para discussão da AI e continuidade do processo de desenvolvimento.

**Comment by raiannyqz** [comment]
A demanda da inception foi realizada após a Arquitetura da Informação #89, Protótipo #96 e Esboço do site #97. Essas tarefas  #89,  #96 e #97 seria um teste para que eu fosse avaliada sobre o meu entendimento de wordpress. Então, quando o esboço do site ficou pronto, mediante as datas de entrega, comuniquei ao @RaniGub que estava me acompanhando nas tarefas e ele pediu para que eu pareasse com @pauloamoreira e apresentasse o que foi realizado, na qual mostrei todo o processo. Ao final ele me perguntou sobre a inception e eu disse que não foi me repassado como tarefa até o momento. 
Sendo que a inception é fundamental para a criação de um site com um todo, sem ela a arquitetura da informação não fica embasada e fica até dificil para quem for compreender o processo de criação do site sem ela. Ela serve também para validar a arquitetura da informação, ou seja tudo o que eu fiz não foi possível validar. Mas porque eu tinha feito as tarefas #89,  #96 e #97 com outro objetivo, o de ver o meu conhecimento de wordpress.
Sendo assim, o próximo passo seria retroceder as etapas, pausar as tarefas #89,  #96 e #97 e realizar a inception. Na qual, foi realizada em dois dias, no primeiro dia eu que coordenei acompanhada por @pauloamoreira e no segundo dia o próprio Paulo que coordenou e eu fiquei observando para entender e aprender a sua metodologia, já que era um processo que eu nunca tinha realizado antes.
Após isso, fiz as modificações no figma (link: https://www.figma.com/file/skXEx8O4RtDCQhxpxxsHgp/Jornadas-e-Arquitetura-da-Informa%C3%A7%C3%A3o-V2?node-id=0%3A1) Tarefa: Jornada #114 e Arquitetura da Informação #89 (https://www.figma.com/file/sBF9hDgBsIM5IXJHQwrUOS/Arquitetura-da-Informa%C3%A7%C3%A3o?node-id=0%3A1)
O próximo passo seria a validação dessas alterações acordando com a inception. Entretanto, nesse período o epic: MVP 1 - Site da Residência #90, na qual esta tarefa (#112) faz parte foi pausada e será repassada para outro bolsista, na qual foi culminado pelo o meu desligamento como bolsista, que foi realizado na reunião no dia 25 de novembro pelo @uira e que estavam também a Dr Alice e @clarissagpeixoto.

**Comment by raiannyqz** [comment]
Em vista disso colocarei esta demanda no Backlog.

**Comment by RaniGub** [comment]
Board apresentada ao Jorge. Em processo de contextualização.

**Comment by RaniGub** [comment]
Board apresentada ao Jorge. Em processo de contextualização.
