### ISSUE TITLE
Site da Residência - Jornada

### ISSUE THREAD

**Issue by raiannyqz** [EscolaDeSaudePublica/sus.ce.gov.br#114]
## **Objetivo**

**Como** pessoa do design e da inovação
**Quero** alinhar as ideias e dados coletados sobre o produto mínimo viável
**Para** ser construído.

## **Contexto**

- Foi criado a Ai e o design do site da residencia da ESP com objetivo inicial de atender aos residente e possíveis residentes e percebemos a necessidade de retroceder algumas etapas para validar esta Ai através da inception. Afim de atender melhor esta demanda.

## **Escopo**

- [x] Quem vai acessar o Site?
- [x] Como a pessoa poderia tomar conhecimento de acesso ao Site pela primera vez?
- [x] O conteúdo do site atende aos anseios das Pessoas Usuárias?

## **Critérios de Aceitação**

- [ ] titulo  
**Dado que** sou pessoa do design e inovação 
**Quando** faço a jornada e
**então** melhoro o resultado da Ai.

## Observações
https://www.figma.com/file/skXEx8O4RtDCQhxpxxsHgp/Jornadas-e-Arquitetura-da-Informa%C3%A7%C3%A3o-V2

**Comment by RaniGub** [comment]
Olá @raiannyqz deixei a tarefa tramitando pelo workspace da Central também ok? Vou deixar essa no DesignLab para que o @pauloamoreira possa controlar a coparticipação.

**Comment by raiannyqz** [comment]
> Olá @raiannyqz deixei a tarefa tramitando pelo workspace da Central também ok? Vou deixar essa no DesignLab para que o @pauloamoreira possa controlar a coparticipação.

Ahh tá ótimo, coloquei o @pauloamoreira na assinatura do inception também!

**Comment by RaniGub** [comment]
Board apresentada ao Jorge. Em processo de contextualização.
