### ISSUE TITLE
Criar página "Treinamento" [COMERCIAL]

### ISSUE THREAD

**Issue by wforte88** [EscolaDeSaudePublica/sus.ce.gov.br#12]
Criar página para solicitação de capacitação chamada "faça sua capacitação"

### Escopo

- [x] Criar botão para fomulário em popup

- [x] Criar formulário para comercial@esp.ce.gov.br com os dados:

**Solicitação de treinamento de uso do Elmo**

**Nome***
[TEXT]

**E-mail***
[TEXT]

**Telefone***
[TEXT]

**Tipo de Unidade de Saúde***
[CHECKBOX]
- Pública (SUS)
- Privada

**Nome da Unidade de Saúde***
[TEXT]

**Cargo/Função na Unidade de Saúde***
[TEXT]

**Quantidade de profissionais a serem treinados**
_Caso deseje solicitar treinamento apenas para você, deixe este campo em branco._
[TEXT]

[CAPTCHA]

[BUTTON]**Enviar**

[CONFIRMAÇÃO]
Sua solicitação foi enviada!
Em breve, nossa equipe lhe informará a melhor forma de atender a sua necessidade de treinamento.

### PubliciLab
- [x] Revisar texto para melhorar o contexto de solicitação dos treinamentos para unidades do SUS e unidades privadas
- [x] Informar o e-mail para envio do formulário. Será comercial@esp.ce.gov.br

### DesignLab
- [x] Revisar layout da página
- [x] Ajustar conteúdos de acordo com proposições do PubliciLab
- [x] Incluir chamada na home page com fotos
- [x] Incluir página no menu principal com o label "Treinamento", logo após "Como Adquirir"

### Observações
Página "Instruções" conterá todos os conteúdos instrucionais abertos.
Imagens autorizadas estão no Drive, na pasta Elmo > Fotos > Fotos Ascom

**Comment by clarissagpeixoto** [comment]
Meninos, segue texto inicial: 

A **_capacitação presencial_** acontece na Escola de Saúde Pública do Ceará, tem duração de quatro horas, é recomendada para profissionais de saúde (médicos, enfermeiros e fisioterapeutas) e é dividida nas seguintes etapas: aula expositiva, montagem do equipamento e simulação realística. Para realizar a capacitação, é necessário realizar agendamento prévio.  Ao final do curso, o aluno receberá certificação da Escola de Saúde Pública do Ceará. Tratando-se de um dispositivo novo de suporte respiratório, **_recomenda-se fortemente_** o treinamento do profissional que irá manuseá-lo, para maior segurança dos pacientes e dos profissionais de saúde.

**Comment by danielgula** [comment]
Modelo de Jornada do usuário:

Botão [Quero fazer meu treinamento]

1. Você é:
- unidade pública
- unidade privada

2. - solicitar individual ou coletivo

3. - dados específicos para envio

**Comment by clarissagpeixoto** [comment]
Daniel, não é "Quero fazer meu treinamento". O correto é: "Solicitar capacitação"

**Comment by clarissagpeixoto** [comment]
Solicito previsão de entrega.

**Comment by ClarisCaval** [comment]
@wforte88, fiz uns ajustes no texto, e umas quebras, para dar uma suavizada na exibição. Veja:

A capacitação presencial é uma atividade realizada pela Escola de Saúde Pública do Ceará (ESP/CE), conduzida por uma equipe interdisciplinar e recomendada para profissionais de saúde (médicos, enfermeiros e fisioterapeutas) que farão o manejo dos capacetes em pacientes com Covid-19.

O curso tem duração de quatro horas e é dividido nas seguintes etapas: aula expositiva, montagem do equipamento e simulação realística. Para realizar a capacitação, é necessário fazer um agendamento prévio. Ao final do curso, o aluno receberá certificação da ESP/CE.

Tratando-se de um dispositivo de saúde, capaz de salvar vidas, recomenda-se fortemente o treinamento dos profissionais que irão manuseá-lo, para maior segurança de todos os envolvidos.

**Comment by ClarisCaval** [comment]
Esse item de 'divulgar o email de envio do formulário' eu não entendi. Divulgar onde? A pessoa já vai poder fazer esse agendamento né?

**Comment by clarissagpeixoto** [comment]
Pessoal, o texto inserido na página não foi o que enviamos inicialmente.

Em ter, 2 de fev de 2021 15:25, Clarisse1983 <notifications@github.com>
escreveu:

**Comment by danielgula** [comment]
Página atualizada em:
https://sus.ce.gov.br/elmo/faca-sua-capacitacao/

Gentileza peço atenção para as tarefas abaixo que necessitam de apoio do Publicilab:
- Preciso do e-mail o qual serão enviadas as mensagens do formulário.
- Penso em substituir, na página inicial, o espaço "Fale com a Gente" e colocar botão de chamada para "Faça sua Capacitação".
- Em adição a chamada, incluir o link para a capacitação no card de aviso em todos os materiais instrucionais.

**Comment by clarissagpeixoto** [comment]
@danielgula @wforte88 Seguem ajustes:

- O texto correto é o que a @Clarisse1983 postou há 2 dias (ver mensagem acima);
- Os quadros de mensagem estão cortando os textos. Favor corrigir; 
- A imagem do Elmo está em baixa resolução, pixelada. Sugiro colocar imagens do treinamento em si. Vou te mandar por e-mail;
- O botão "solicitar capacitação" não está dentro do padrão dos botões do site (animação e layout). Seria importante seguir o mesmo padrão. Ver botão: "Manual de referência do utilizador";
- Não vejo necessidade dessa "soma" ao final do formulário. É mesmo necessário?
- Sugiro rediagramar o formulário de maneira a dar fluidez à leitura.
- "Solicitação de treinamento de uso do Elmo" deve ser substituída por "Solicitação de treinamento"
- Remover: "Caso deseje solicitar treinamento apenas para você, deixe este campo em branco."


Atc,
Clarissa.

**Comment by clarissagpeixoto** [comment]
Pessoal, a página não para de carregar, a diagramação do formulário ainda não tá legal, tá quebrada e continuo achando desnecessário essa soma ao final do formulário. @saracafe e @Clarisse1983, precisamos pensar em dois textos (para a caixa posterior ao preenchimento do formulário): um para os usuário do setor público e outro pra os usuários do setor privado.

**Comment by ClarisCaval** [comment]
Reunimos agora para encaminhar a finalização da tarefa e ajustamos que:
- Daniel vai trabalhar em ajustes no layout, tais como: trazer elementos iconográficos para informações pontuais como tempo de treinamento e certificação;
- Foto será substituída por outra com componente humano. Clarissa tentará produzir um registro real de treinamento ou utilizaremos uma foto já disponível editada;
- Fonte do botão do formulário seguirá padrão de maiúsculas e minúsculas;
- Daniel vai propor alterações no formulário, especialmente tentando harmonizar o que ficou sem grid aleatoriamente;
- E redefinimos o prazo de entrega para segunda-feira, 08/02.

**Comment by ClarisCaval** [comment]
@danielgula, demos uma olhada na nova proposta e vejo que:
- a foto melhorou, mas é provisória, ainda não é a ideal;
- o formulário de solicitação também ficou muito melhor;
- a iconografia ficou ruim, se essa foi a proposta possível, preferimos sem.
As finalizações agora cabem a vocês, DesignLab. ;)

**Comment by danielgula** [comment]
@Clarisse1983 , segue registro da demanda para validação do Publicilab:
Tanto a foto como os ícones foram marcação de layout na versão anterior. Fizemos os seguintes ajustes:

- Diagramação dos textos, utilizando ícones de tópicos e subtítulos para uma melhor experiência narrativa;
- Inclusão de uma foto tratada escolhida no último pareamento, como alternativa a uma produzida, que demoraria ainda mais tempo

Caso essa UI esteja adequada dentro da proposta de experiência, refinamos a experiência mobile e finalizamos essa tarefa específica.

**Comment by ClarisCaval** [comment]
@danielgula, gostei bastante das alterações! Parabéns!
Vou pedir para ajustar só um detalhe: onde tem agendamento e certificado, vamos deixar só a informação do certificado, para evitar dar a entender que é só agendar, quando alguns também precisarão pagar pelo curso. Aí esse agendamento a própria @clarissagpeixoto faz a partir do contato por email.

**Certificação**
Os profissionais capacitados recebem certificado de participação emitido pela ESP-CE.

**Comment by danielgula** [comment]
A página,
https://sus.ce.gov.br/elmo/faca-sua-capacitacao/
foi aprovada e seguirá para o fluxo de links no site.

**Comment by danielgula** [comment]
De acordo com orientações do GT Elmo, substituímos a palavra Certificação por Declaração de Participação, ficando o texto dessa forma:

**Participação**
Os profissionais capacitados recebem declaração de participação emitida pela ESP-CE.

**Comment by clarissagpeixoto** [comment]
Pessoal, em reunião hoje como pessoal do grupo do GT, levantou-se a possibilidade de ser cobrado um valor também para os profissionais da rede pública de outros estados. Isso ainda irá ser definido. Passo para vocês a decisão posteriormente.

**Comment by danielgula** [comment]
Update da tarefa: estamos aguardando a liberação e testes do email comercial@esp.ce.gov.br por parte do time da infra para liberar a página.

**Comment by danielgula** [comment]
A página foi concluída, com o formulário enviando os dados para o Frashdesk, até quando tivermos a liberação do email comercial pela infra.

**Comment by clarissagpeixoto** [comment]
Pessoal, segue texto correto:
Sua solicitação foi enviada! Em breve, nossa equipe entrará em contato com você, por e-mail ou por telefone, para atender à sua solicitação. Fique atento!

**Comment by danielgula** [comment]
Texto de mensagem de êxito alterado.
