### ISSUE TITLE
Inserir e-mails institucionais nos perfis

### ISSUE THREAD

**Issue by danielgula** [EscolaDeSaudePublica/sus.ce.gov.br#122]
## **Objetivo**

**Como** internauta
**Quero** acessar os perfis dos felicilabers  
**Para** ver os emails institucionais

## **Contexto**

A partir de solicitações externas, precisamos incluir os e-mails institucionais dos felicilabers, gerando mais vínculos com a ESP de forma profissional.

## **Escopo**

- [x] Levantar emails a partir do Zimbra e lista da DIT
- [x] Atualizar o documento dos perfis
- [x] Criar botão "Meu e-mail" na coluna "Estou por aqui"

## **Critérios de Aceitação**

**Dado que** estou no site Felicilab
**Quando** acesso algum perfil
**então** vejo um botão de contato com o felicilaber

**Comment by raiannyqz** [comment]
Os emails foram inseridos no arquivo: https://docs.google.com/document/d/1TOuIFa7Ds1cOlgOmvkFQIIt2Jgnl2m2abn1VJUil1F4/edit#

**Comment by danielgula** [comment]
Time colaborou com a demanda e ela se encontra atendida. Issue encerrada.
