### ISSUE TITLE
Criar seção do Edital 26 no site Felicilab

### ISSUE THREAD

**Issue by danielgula** [EscolaDeSaudePublica/sus.ce.gov.br#128]
## **Objetivo**

**Como** futuro candidato
**Quero** acessar o site do felicilab
**Para** ver detalhes sobre o Edital 16

## **Contexto**

- Para ajudar os futuros candidatos do Edital 26 a entenderem e se inscreverem no edital, precisamos criar uma seção no site com informações instrucionais sobre o certame.

## **Escopo**

- [x] Criar página do edital (data e infográfico)
- [ ] Criar página orientações (tutoriais e depoimentos)
- [x] Criar página com dúvidas do edital (FAQ)

## **Critérios de Aceitação**

**Dado que** estou na internet
**Quando** acesso o site do Felicilab
**então** vejo informações sobre o edital 26

## **Outras Informações**
https://sus.ce.gov.br/felicilab/duvidas-do-edital/

**Comment by danielgula** [comment]
@Clarisse1983 a página do FAQ foi atualizada e aguarda aprovação.

**Comment by ClarisCaval** [comment]
Aqui gente, avaliem, opinem:
https://sus.ce.gov.br/felicilab/edital-26-2021/

**Comment by ClarisCaval** [comment]
@danielgula, alterar esse texto:

Se você tem dúvidas sobre o Edital 26/2021, entre em contato com a ESP através do e-mail edital262021@esp.ce.gov.br. Também criamos uma seção especial com as principais informações, que você acessa aqui: (e leva para o FAQ, porque esse modelo flutuante de menu é meio confuso, nem todo mundo vai encontrar).
