### ISSUE TITLE
Produzir apresentação das entregas do NIT/Felicilab em 2021

### ISSUE THREAD

**Issue by danielgula** [EscolaDeSaudePublica/sus.ce.gov.br#129]
## **Objetivo**

**Como** usuária  
**Quero** acessar o site felicilab
**Para** ver as entregas do laboratório em 2020/2021

## **Contexto**

A partir do levantamento de entregas do laboratório levantadas pela equipe do Publicilab, alguns eventos importantes precisam entrar no site, como uma retrospectiva em linha do tempo. Serão criados posta específicos de cada entrega no site que, quando reunidos em uma linha do tempo, dão a dimensão da importância e das contribuições do time na inovação em saúde no Ceará.

## **Escopo**

- [x] Pesquisar plugin no WP de timeline para posts
- [x] Configurar plugin
- [x] Criar datas em doc compartilhado com foto, título, data e texto descritivo
- [x] Anexar datas à timeline
- [x] Testar experiência mobile
- [x] Incluir o item [Nossa História] na página inicial do site

## **Critérios de Aceitação**

**Dado que** estou no site felicilab
**Quando** acesso a página inicial
**então** vejo os principais eventos e entregas do Felicilab

**Comment by danielgula** [comment]
Em conversa com @Clarisse1983 nós iremos usar o javascript da Knightlabs para a timeline, que já usada no site da ESP e no Elmo. Teremos uma seção na home chamada "Nossa História". Os dados serão colocados em uma planilha do Google, para o ano de 2021, a partir de um doc da @saracafe.

**Comment by uira** [comment]
@danielgula eu tinha feito a sugestão de postagens com foto, pra rechear nosso site... 

Não deu?

**Comment by danielgula** [comment]
@uira a gente optou em construir a timeline com entradas fixas (nós conseguimos colocar os posts depois) dentro da planilha do plugin atual que usamos para timeline, que vai se chamar "Nossa História" e ficará na home do site. Teremos inicialmente as entregas de 2021, para a ReuniãoZona, conforme acordo com a @Clarisse1983. @saracafe e @raiannyqz estão montando as entregas, enquanto que eu montei o ambiente. Segue abaixo os links para a página temporária com a timeline e o link da planilha para inserir os dados.
https://sus.ce.gov.br/felicilab/fake-timeline/
https://docs.google.com/spreadsheets/d/1RiHfWjyVI9Z1qMw6zgqnleJNJLzoMj7Rj_zOemmBI9s/edit#gid=0

**Comment by danielgula** [comment]
Seção criada na home do site Felicilab. Iremos fazer em breve atualização com novas entradas e provavelmente um melhor estudo de AI para os conteúdos e usabilidade.
