### ISSUE TITLE
Revisar Levantamento de Requisitos para o site das Residências

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/sus.ce.gov.br#144]
## **Objetivo**

**Como** designer  
**Quero** me contextualizar do Levantamento de Requisitos para o Site da Residência
**Para** validar iniciar o processo de desenvolvimento

## **Contexto**

Os residentes precisam de um site para melhorar o relacionamento com os programas de Residência e este, por sua vez, requer uma melhor visibilidade do seu conteúdo informativo. Os possíveis ingressantes precisam obter informações a cerca do programa, dos editais, bem como indicativos e outros assuntos que possa interessar a sua participação. Neste sentido, devemos criar um site que possa habilitar essa interação do residente e possíveis ingressantes para com o programa servindo como canal informativo e de comunicação.

## **Escopo**

- [x] Revisar Levantamento de Requisitos

## Observações
Links de apoio e informações adicionais

**Comment by elpadrejorge** [comment]
Durante a revisão surgiram algumas dúvida que serão pareadas com o @RaniGub  e @danielgula . Aguardando retorno de sua disponibilidade. 
Previsão Rani : Sexta 11/03, das 9 às 10 horas.
Previsão do Daniel: Aguardando retorno.

**Comment by RaniGub** [comment]
> Durante a revisão surgiram algumas dúvida que serão pareadas com o @RaniGub e @danielgula . Aguardando retorno de sua disponibilidade. Previsão Rani : Sexta 11/03, das 9 às 10 horas. Previsão do Daniel: Aguardando retorno.

@elpadrejorge fará um pareamento com @pauloamoreira hoje 10h15 para ficar atualizado sobre os tópicos da residência.

**Comment by uira** [comment]
@RaniGub Quero conversar com vcs sobre isso, @RaniGub e @elpadrejorge

**Comment by RaniGub** [comment]
> @RaniGub Quero conversar com vcs sobre isso, @RaniGub e @elpadrejorge
Conversamos hoje de tarde na ESP.
