### ISSUE TITLE
Publicar novos artigos na biblioteca

### ISSUE THREAD

**Issue by danielgula** [EscolaDeSaudePublica/sus.ce.gov.br#150]
## **Objetivo**

**Como** persona  usuária
**Quero** acessar o site do elmo
**Para** ver as novas publicações na Biblioteca

## **Contexto**

Novas publicações foram feitas no site do Elmo, mas no campo e notícias. Precisamos colocar esses documentos na aba Biblioteca. As publicações precisam aparecer primeiro.

## **Escopo**

- [x] baixar arquivos pdf originais
- [x] pesquisas capas e dados catalográficos
- [x] criar projetos na biblioteca
- [x] publicar alterações

## **Critérios de Aceitação**

**Dado que** estou no site Elmo
**Quando** acesso o link Biblioteca
**então** vejo as novas publicações do Elmo

## Observações
https://sus.ce.gov.br/elmo/elmo-uma-nova-interface-de-capacete-para-cpap-para-tratar-insuficiencia-respiratoria-hipoxemica-aguda-relacionada-ao-covid-19-fora-da-uti-um-estudo-de-viabilidade-em-ingles-e-portugues/

https://sus.ce.gov.br/elmo/elmo-uma-interface-inovadora-para-ventilacao-nao-invasiva-em-ingles-e-portugues/

**Comment by danielgula** [comment]
@clarissagpeixoto demanda atendida. É preciso solicitar que a Ascom da ESP ao invés de colocar os arquivos para baixar possa fazer um link direto para cada publicação na biblioteca, ou simplesmente remover os dois posts.

**Comment by clarissagpeixoto** [comment]
Perfeito, Dan! Obrigada. Já repassei para a Alice.

**Comment by danielgula** [comment]
Demanda atendida

**Comment by danielgula** [comment]
Conforme contato por email de @clarissagpeixoto colocamos essa publicação na Biblioteca em português
