### ISSUE TITLE
Incluir mini currículo na seção treinamento - ELMO

### ISSUE THREAD

**Issue by alesouza88** [EscolaDeSaudePublica/sus.ce.gov.br#168]
[MINICURRICULO_Site Elmo_acrescentar.docx](https://github.com/EscolaDeSaudePublica/sus.ce.gov.br/files/9559706/MINICURRICULO_Site.Elmo_acrescentar.docx)
ESPCE#20220913586918 — Incluir mais um currículo na seção treinamento

De: Clarissa Gomes Peixoto
Para: FELICILAB
Assunto: Incluir mais um currículo na seção treinamento

Anexo: MINICURRICULO_Site Elmo_acrescentar.docx , 85.9 KBytes

Gente, surgiu mais um mini currículo para a seção EQUIPE - EQUIPE DE TREINAMENTO.
Por favor, fazer a inclusão. Segue arquivo anexo.

**Comment by danielgula** [comment]
Inclusão feita.

**Comment by alesouza88** [comment]
Chamado fechado com sucesso
