### ISSUE TITLE
Incluir fotos na seção de materiais instrucionais - site ELMO

### ISSUE THREAD

**Issue by alesouza88** [EscolaDeSaudePublica/sus.ce.gov.br#169]
De: Clarissa Gomes Peixoto 
Para: FELICILAB 
Assunto: Incluir fotos na seção de materiais instrucionais

Na seção a seguir https://sus.ce.gov.br/elmo/equipamentos-e-materiais-para-o-correto-funcionamento-do-sistema-elmo-cpap/  incluir fotos dos respectivos itens para o correto funcionamento do sistema Elmo. 

As fotos encontram-se aqui: https://drive.google.com/drive/folders/1a0UMGQpJ0r-QoLY0Uji2bxlwaf6xs_zZ

**Comment by danielgula** [comment]
@alesouza88 e @clarissagpeixoto vejam como ficou o resultado na página
https://sus.ce.gov.br/elmo/equipamentos-e-materiais-para-o-correto-funcionamento-do-sistema-elmo-cpap/

**Comment by clarissagpeixoto** [comment]
Pessoal, a foto do produto "2 látex para fluxômetros de 30L|min" está errada. Favor fazer a correção. Segue imagem correta em anexo.
![mangueira](https://user-images.githubusercontent.com/77675469/192813378-ffc72112-6d50-4b54-9cca-f41e96782aa3.jpg)

**Comment by clarissagpeixoto** [comment]
ps.: a foto não é muito boa, mas não consegui uma melhor.

**Comment by alesouza88** [comment]
Alterações realizadas conforme solicitadas.
Isto posto, seguiremos com fechamento da issue (obs: é minha 1ª issue que fecho) 😜

![image](https://user-images.githubusercontent.com/87095371/194579006-8e1dc5ce-1609-40ae-a12f-ff0711d5785a.png)
