### ISSUE TITLE
Criar página "O Elmo"

### ISSUE THREAD

**Issue by wforte88** [EscolaDeSaudePublica/sus.ce.gov.br#17]
Criar página institucional de apresentação do Elmo.

### PubliciLab

- [x] Revisar textos de apresentação
- [x] Redigir informações sobre a patente
- [x] Redigir textos e indicar imagens para a linha do tempo de desenvolvimento do Elmo (verificar notícias do site e vídeo de resultados preliminares)
- [x] Uniformizar texto do "[Quem é quem](https://drive.google.com/drive/u/0/folders/1X7jE-f4TDNK1GiR2qpNghfQC_fgSG7Jv)"
- [x] Refinar a Timeline com fotos e títulos
- [x] Ver a possibilidade de quebrar o texto "O que é o Elmo" para inserir uma nova seção "A Patente"

### DesignLab
- [x] Desenvolver layout da página com o conteúdo indicado pelo PubliciLab
- [x] Inserir conteúdos indicados pelo Publicilab
- [x] Implemenatar a Timeline JS
- [x] Inserir fotos e bio dos currículos
- [x] Ajustar títulos
- [x] Recolocar teste de conceito
- [x] Ajustar texto para justificado
- [x] Validar bios com Ascom
- [x] Ver experiência mobile

**Comment by saracafe** [comment]
Texto revisado https://docs.google.com/document/d/1Ii187YvnGm21rSX6rPf5pLFB2auIqz2ivUB8-ghzlH4/edit?usp=sharing
