### ISSUE TITLE
Correção nome de instrutores - site ELMO

### ISSUE THREAD

**Issue by alesouza88** [EscolaDeSaudePublica/sus.ce.gov.br#170]
ESPCE#20220913586919 — Correção

De: Clarissa Gomes Peixoto
Para: FELICILAB
Assunto: Correção

Correção:
**1. O nome da instrutora Andrea Stopiglia Guedes Braide está com o nome da Patrícia Elisabeth da Silva (quando vc clica em cima do mini currículo da Andrea). Fazer a correção.

2. Substituir "Ingrid Lima" por "Ingrid Sá Cavalcante" (interna e externamente).**

**Comment by danielgula** [comment]
Alterações realizadas

**Comment by alesouza88** [comment]
Chamado fechado com sucesso
