### ISSUE TITLE
Banners site do Elmo

### ISSUE THREAD

**Issue by alesouza88** [EscolaDeSaudePublica/sus.ce.gov.br#171]
## **Inserir Banners rotativos no site do Elmo**

Como: pessoa responsável pelo site do Elmo
Quero: transformar a imagem estática da página inicial do capacete Elmo em banners rotativos
Para: publicizar as ações referentes ao capacete Elmo 

## **Contexto**

-

## **Escopo**

- [ ] escopo1

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [ ] titulo  
**Dado que** algo  
**Quando** faço  
**então** resulta

## Observações
Atividade proveniente da Central de chamados OTRS
Título do chamado: ESPCE#20221109587155 — Banners site do Elmo
Link do chamado: https://centraldesuporte.esp.ce.gov.br/otrs/index.pl?Action=AgentTicketZoom;TicketID=8019
Solicitante: Clarissa Gomes Peixoto

**Comment by alesouza88** [comment]
ESPCE#20221109587155 — Banners site do Elmo

![image](https://user-images.githubusercontent.com/87095371/201413257-40a17d5d-eaed-4088-af86-14d88df869a4.png)

**Comment by clarissagpeixoto** [comment]
Oi, gente! Como anda essa demanda? Algum prazo de entrega?

**Comment by alesouza88** [comment]
> 

Oi Clarissa, bom diaa !!!

@danielgula, pode nos atualizarr? Beijossss

**Comment by danielgula** [comment]
Boa tarde. A implementação foi feita. Colocamos dois banners genéricos para testar a funcionalidade que se encontra validada e ok.
Precisamos organizar qual vai ser o fluxo de inclusão dos banners alinhando com Ascom/Ditec/Felicilab. Pode ser usado o mesmo que fazemos com o hotsite coronavirus: Ascom faz as imagens demandas pela Ditec e Felicilab implementa.

**Comment by clarissagpeixoto** [comment]
Daniel, por favor, enviar formato do banner pro Julio, da ASCOM. Ele está com a demanda parada, aguardando essa medida.

**Comment by danielgula** [comment]
Passando para lembrar que os formatos foram passados desde semana passada.

**Comment by alesouza88** [comment]
> Passando para lembrar que os formatos foram passados desde semana passada.

Dan, me avisa quando tiver prontooo. 

Bjaooo

**Comment by danielgula** [comment]
Todos os banners foram criados no site conforme layout da Ascom, porém não foram fornecidos os links dessas chamadas.

**Comment by uira** [comment]
@danielgula

**Comment by alesouza88** [comment]
A solicitação de implementação do banner rotativo foi realizada.

Chamado fechado. ESPCE#20221109587155 — Banners site do Elmo
