### ISSUE TITLE
Reativação de aba no site Coronavírus Ceará

### ISSUE THREAD

**Issue by alesouza88** [EscolaDeSaudePublica/sus.ce.gov.br#172]
## **Objetivo**

Como: pessoa responsável pelo site Coronavírus Ceará
Quero: reativar aba no site Coronavírus
Para: Visualizar informações do site Coronavírus

## **Contexto**

-

## **Escopo**

- [ ] escopo1

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [ ] titulo  
**Dado que** algo  
**Quando** faço  
**então** resulta

## Observações
Demanda proveniente do chamado - ESPCE#20221121587189 — Aba no site Coronavírus Ceará
Link do chamado: https://centraldesuporte.esp.ce.gov.br/otrs/index.pl?Action=AgentTicketZoom;TicketID=8053
Solicitante: Júlio Cesar Alves Lopes

![image](https://user-images.githubusercontent.com/87095371/204050390-bbab5923-a2a6-4d77-96c3-fd9da7cf06f0.png)

**Comment by danielgula** [comment]
Conforme enunciado no email, reativamos a aba de notícias no hotsite da vacinação.
Havendo outros links para serem reativados, eles precisam ser especificados exatamente para podermos localizar e reativar também.

**Comment by alesouza88** [comment]
Valeu Dan.

Chamado encerrado
