### ISSUE TITLE
Adaptar conteúdo "7 dicas rápidas de uso do Elmo" para aba no vídeo "Princípios de uso"

### ISSUE THREAD

**Issue by wforte88** [EscolaDeSaudePublica/sus.ce.gov.br#20]
## **Objetivo**

**Como** usuário
**Quero** acessar o link princípios de uso
**Para** ver 7 dicas rápidas do Elmo

## **Contexto**

Foi pensada uma página de 7 dicas de uso do Elmo, mas decidimos colocar esse conteúdo como aba na página Princípios de Uso

## **Escopo**

- [x] Criar aba
- [x] Criar lista de dicas na aba
- [x] Inserir popup: Definir tamanho do Elmo
- [x] Inserir popup: Montar o Sistema Elmo
- [x] Inserir popup: Checar vazamentos
- [x] Inserir popup: Colocar o Elmo
- [x] Inserir popup: Titular a FiO2
- [x] Inserir popup: Titular e medir a pressão
- [x] Inserir popup: Retirar o Elmo
- [x] Atualizar novos conteúdos a partir dos vídeos instrucionais enviados pelo time Elmo

## **Critérios de Aceitação**

**Dado que** estou no site do Elmo
**Quando** acesso o link "Princípios de uso"
**Então** vejo 7 dias de uso do Elmo em uma aba

**Comment by wforte88** [comment]
Material de referência:
[ELMO-DICAS RÁPIDAS.pptx](https://github.com/EscolaDeSaudePublica/sus.ce.gov.br/files/6458725/ELMO-DICAS.RAPIDAS.pptx)
[Manual ELMO.pdf](https://github.com/EscolaDeSaudePublica/sus.ce.gov.br/files/6458727/Manual.ELMO.pdf)

**Comment by danielgula** [comment]
Ajustes feitos na página para revisão:
https://sus.ce.gov.br/elmo/project/principios-de-uso/

**Comment by marameida** [comment]
@uira e Alice aprovamos esse material com vocês e Dr Marcelo? Pedimos orientação para fechamento dessa atividade.

**Comment by marameida** [comment]
Repassado link para Cleo (CEDES) para validação final.
https://sus.ce.gov.br/elmo/project/principios-de-uso/

**Comment by marameida** [comment]
Conversado presencialmente com Cleo e Clayton para validação do material com equipe de pesquisadores do ElmoLab.

**Comment by marameida** [comment]
Será validado por Rafael e Betina

**Comment by marameida** [comment]
Repassado material (vídeos e arquivo em pdf), elaborado por Betina e Rafael, ao @danielgula, para ajustes necessários.

**Comment by marameida** [comment]
Acordado em reunião com @danielgula a realização dos ajustes sugeridos.

**Comment by marameida** [comment]
Agendado momento com @danielgula para encerramento desta atividade.

**Comment by marameida** [comment]
No aguardo ainda por retorno do Designlab.

**Comment by marameida** [comment]
@danielgula está em contato direto com o CEDES, para finalizar demanda.

**Comment by marameida** [comment]
Reunião agendada com @danielgula para demandas junto ao Designlab. 

Data: 10/08/21
Horário: 9:30

**Comment by danielgula** [comment]
Rafael do CEDES está verificando as alterações para nos passar.

**Comment by marameida** [comment]
Ainda no aguardo por retorno com Rafael do CEDES.

**Comment by marameida** [comment]
Enviado videos e audios recebidos pelo CEDES ao Designlab (@danielgula ).

**Comment by danielgula** [comment]
Todas as alterações foram feitas na página
https://sus.ce.gov.br/elmo/project/principios-de-uso/
