### ISSUE TITLE
Desenvolver subsite do Elmo

### ISSUE THREAD

**Issue by wforte88** [EscolaDeSaudePublica/sus.ce.gov.br#3]
Lista de links do site
Home principal
O Elmo
Capacitação
Resultados
Adquira o Elmo
Faça seu treinamento
Tira-dúvidas

**Comment by danielgula** [comment]
Este épico será encerrado, pois o subsite do Elmo já foi entregue e está no ar. Novas demandas serão tratadas em um novo épico ou como atualizações de rotina.
