### ISSUE TITLE
Melhorar arquitetura do site

### ISSUE THREAD

**Issue by clarissagpeixoto** [EscolaDeSaudePublica/sus.ce.gov.br#30]
## **Objetivo**

**Como** pessoa usuária do site Elmo 
**Quero** encontrar informações mais rapidamente 
**Para** entender melhor o funcionamento do Elmo

## **Contexto**
Hoje as informações do site do Elmo estão alocadas de maneira desordenada, sendo difícil o acesso a determinados conteúdos.

-

## **Escopo**

- [ ] escopo1

## **Fora de Escopo**

- fora_de_escopo

## **Critérios de Aceitação**

- [ ] titulo  
**Dado que** algo  
**Quando** faço  
**então** resulta

## Observações
Links de apoio e informações adicionais

**Comment by danielgula** [comment]
Esta demanda já está sendo tratada em outro card (abaixo citado). Portanto podemos fechar essa issue.
https://github.com/EscolaDeSaudePublica/sus.ce.gov.br/issues/29
