### ISSUE TITLE
Página "Como doar"

### ISSUE THREAD

**Issue by clarissagpeixoto** [EscolaDeSaudePublica/sus.ce.gov.br#32]
## **Objetivo**

**Como** doador
**Quero** fazer uma doação de Elmos ou treinamentos
**Para** para ajudar as instituições de saúde públicas ou privadas (prefeituras, governo do Estado, pequenos hospitais etc) no combate à Covid-19.

## **Contexto**

Estamos vivendo um momento de pandemia. Por esse motivo, muitas instituições privadas e até pessoas físicas têm demonstrado interesse em fazer doações para a ESP (**tanto de Elmos quanto de treinamentos**). Nesse contexto, gostaríamos de abrir um item no menu do site do Elmo para abrir iniciar o contato com essas pessoas/instituições. 

## **Escopo**

- [x] Criar seção dentro da página doações
- [x] Inserir conteúdo fornecido pela Ascom
- [x] Inserir números específicos de doações à ESP
- [x] Verificar experiência mobile

## **Critérios de Aceitação**

**Dado que** algo  
**Quando** faço  
**então** resulta

## Observações
Links do conteúdo
https://docs.google.com/document/d/1Ii187YvnGm21rSX6rPf5pLFB2auIqz2ivUB8-ghzlH4/

**Comment by danielgula** [comment]
Página criada em
https://sus.ce.gov.br/elmo/doacoes/
