### ISSUE TITLE
Mudar "capacitações" por "treinamentos" no botão novo do site

### ISSUE THREAD

**Issue by clarissagpeixoto** [EscolaDeSaudePublica/sus.ce.gov.br#33]
## **Objetivo**

**Como** usuário
**Quero** acessar o site Elmo
**Para** ver o link de menu Treinamento

## **Contexto**

Para melhor entendimento dos usuários, deve-se colocar o nome Treinamento no menu do site, ao invés de capacitação.

## **Escopo**

- [x] Alterar nome do menu

## **Critérios de Aceitação**

**Dado que** estou no site do Elmo
**Quando** acesso o menu do site
**Então** vejo o link com o nome Treinamento

**Comment by danielgula** [comment]
Link alterado no menu
https://sus.ce.gov.br/elmo/
