### ISSUE TITLE
Incorporar vídeo no site do Elmo

### ISSUE THREAD

**Issue by julio-alveslopes** [EscolaDeSaudePublica/sus.ce.gov.br#36]
**Como** usuário
**Quero** acessar o site do Elmo
**Para** ver o vídeo de apresentação do capacete

## **Contexto**

Substituir foto pelo vídeo explicativo "O que é o Elmo?"
https://youtu.be/WhKI8HWxDt0

## **Escopo**

- [x] - trocar elemento de imagem na página inicial pelo elemento de vídeo

## **Critérios de Aceitação**

**Dado que** estou no site do Elmo
**Quando** acesso a página inicial
**então** visualizo o vídeo introdutório do Elmo

## Observações
https://youtu.be/WhKI8HWxDt0

**Comment by danielgula** [comment]
O vídeo foi inserido nos seguintes locais:
Página Inicial (substituindo imagem)
Página "O Elmo" - https://sus.ce.gov.br/elmo/o-elmo/
Página de instruções - https://sus.ce.gov.br/elmo/project/introducao-ao-capacete-elmo/
