### ISSUE TITLE
Criar página "Doações"

### ISSUE THREAD

**Issue by wforte88** [EscolaDeSaudePublica/sus.ce.gov.br#39]
## **Objetivo**

**Como** usuária do site do Elmo  
**Quero** ter acesso a informações sobre doações
**Para** saber o impacto das doações na distribuição do Elmo para as unidades de saúde

## **Contexto**

Desde dezembro de 2020, algumas entidades se mobilizaram para adquirir Elmos e doá-los a unidades de saúde com sobrecarga de atendimento a pacientes graves com Covid-19. Seguindo o princípio da transparência, é necessário publicizar a quantidade de dispositivos doados e registrar o histórico de notícias sobre a distribuição desses equipamentos.

## **Escopo**

- [x] Criar subpágina "Doações" (filha de "O Elmo")
- [x] Inserir card com quantidade de dispositivos doados
- [x] Inserir portfólio de projetos na categoria "Doações"
- [x] Analisar destaque da página "Doações" na home page. Alinhar com a Ascom.

## **Critérios de Aceitação**

- [x] Página doações
**Dado que** acesso o site sus.ce.gov.br/elmo  
**Quando** clico no menu O Elmo > Doações  
**então** devo visualizar o conteúdo da página de acordo com o escopo definido

## Observações
Publicação de notícias e atualização de métricas são executadas pela Ascom.

**Comment by wforte88** [comment]
**Ajustes necessários**

- [x] Na frase dos indicadores, alertar "elmos doados à Saúde do Ceará" para "Elmos doados ao SUS no Ceará"
- [x] Substituir "Quem doa:" por "Últimas doações"

**Comment by wforte88** [comment]
**Alteração de escopo**
A Ascom solicitou maior destaque para a página "Doações". Foi incluído no escopo a inserção na home page de um bloco para a página.

**Comment by danielgula** [comment]
Página criada em
https://sus.ce.gov.br/elmo/doacoes/
