### ISSUE TITLE
Definir arquitetura da informação

### ISSUE THREAD

**Issue by wforte88** [EscolaDeSaudePublica/sus.ce.gov.br#44]
## **Objetivo**

**Como** designer  
**Quero** desenhar a estrutura de informação do PPP
**Para** planejar essa estrutura no subsite

## **Contexto**
O PPP é um documento formal de 125 páginas. É necessário adaptá-lo para páginas HTML que facilitem o acesso e a localização das informações específicas em um subsite do SUS.CE.

## **Escopo**

- [x] Analisar sumário do PPP
- [x] Propor AI do subsite
- [x] Definir taxonomia do subsite
- [x] Disponibilizar arquivo AI PPP 2020 na pasta do projeto

## **Critérios de Aceitação**

AI do subsite  
**Dado que** acesso a pasta do PPP no Drive
**Quando** abro o arquivo AI PPP 2020
**então** devo visualizar a taxonomia completa e hierarquizada

## Observações
- [Documento base](https://drive.google.com/file/d/17IJ3TEih7wYPHseUnsAfNFZ-_gCSoo5M/view?usp=sharing)
- Referências de AI
[AI conceitual do Manejo Clínico v3](https://miro.com/app/board/o9J_lR2-1ZQ=/?moveToWidget=3074457355846647106&cot=14)
[Taxonomia do subsite](https://docs.google.com/spreadsheets/d/1_n1fGnDNvU2eyjgcRhXLwFO6BTmN3dGqg-lHnH2sPKc/edit#gid=0)

**Comment by danielgula** [comment]
Devido à urgência da demanda, a arquitetura foi criada em documento compartilhado com os gestores e foi refinada durante o processo de desenvolvimento do MVP1.
Link para acesso: https://docs.google.com/document/d/1ZAIoi6TWVtst7jBxcyWja5mGayFr5O2s7yeac3DCCPE/edit
No próximo MVP serão alocadas horas para um estudo melhor da arquitetura.
