### ISSUE TITLE
Remover carrinho do formulário e dar destaque ao número de alunos.

### ISSUE THREAD

**Issue by marameida** [EscolaDeSaudePublica/sus.ce.gov.br#47]
## **Objetivo**

**Como** usuário do site do elmo
**Quero** remover a figura do carrinho da página "treinamento" e e deixar em destaque o número de alunos;
**Para** não vincular a ideia direta de compra ao tomador de serviço e permitir melhor preenchimento da solicitação de treinamento.

## **Contexto**
O solicitante de treinamento visualiza a imagem de um  "carrinho de compra" quando seleciona a modalidade de treinamento.

## **Escopo**

- [ ] Retirar a imagem do carrinho, incluindo outra;
- [ ] Dar destaque ao preenchimento na quantidade de alunos;

## **Fora de Escopo**

- Vincular o treinamento à um produto de compra.

## **Critérios de Aceitação**

**Dado que**acesso o site do elmo
**Quando**  clico na solicitação de treinamento
**então**consigo ver melhor a quantidade de alunos. 

# Observações

https://sus.ce.gov.br/elmo/faca-sua-capacitacao/

**Comment by danielgula** [comment]
Conforme conversado com @wforte88 e @marameida, não será possível realizar esta issue.
Motivo: o código utilizado para os formulários no site é de terceiros e não pode ser modificado em sua forma e estilo.
