### ISSUE TITLE
E-mail de confirmação de novo usuário não consegue ser enviado

### ISSUE THREAD

**Issue by danielgula** [EscolaDeSaudePublica/sus.ce.gov.br#49]
## **Objetivo**

**Como** usuário do sus.ce
**Quero** receber email de cadastro de novo usuário
**Para** completar o cadastro de usuário

## **Contexto**

Quando um administrador do sus.ce tenta criar um novo usuário e envia a solicitação por email para a pessoa, o email não chega ao destinatário. Analisando o plugin WPmail SMTP percebemos um erro de configuração:

EMAIL DELIVERY ERROR: the plugin WP Mail SMTP v2.5.1 logged this error during the last time it tried to send an email:

Mailer: Default (none)
PHPMailer was able to connect to SMTP server but failed while trying to send an email.
Consider running an email test after fixing it.

A infra precisa fornecer uma solução para o envio de emails pela rede.

## **Escopo**

- [x] refinar problema com a infra de TI
- [x] acompanhar mudanças
- [x] testar mudanças
- [x] documentar procedimento

## **Critérios de Aceitação**

**Dado que** estou como administrados da rede sus.ce
**Quando** crio um usuário novo
**então** o novo usuário recebe o email para completar seu cadastro

**Comment by RaniGub** [comment]
@danielgula verificar se o erro persiste. Se sim, seguir o escopo da tarefa.

**Comment by danielgula** [comment]
Foi aberto chamado com a Infra sobre o ocorrido. O número de acompanhamento é o 20211124585143

**Comment by danielgula** [comment]
Em 21/12 fizemos teste para usuário externo e o email de convite não chegou.

**Comment by danielgula** [comment]
Testes e configurações adicionais foram feitas. A demanda foi atendida e documentação dos procedimentos estão no Drive do sus.ce na subpasta Projetos do Felicilab
