### ISSUE TITLE
Upgrade do site felicilab versão "emergencial"

### ISSUE THREAD

**Issue by danielgula** [EscolaDeSaudePublica/sus.ce.gov.br#54]
## **Objetivo**

**Como** usuário
**Quero** acessar o site do felicilab
**Para** ter uma melhor experiência de navegação

## **Contexto**

Com as demandas de publicação de conteúdo urgentes a serem publicadas na internet, foi criada uma versão simplificada do site do felicilab, no endereço https://sus.ce.gov.br/felicilab/

## **Escopo**

- [x] alterar largura do site
- [x] ajustar fontes
- [x] ajustar menu
- [x] ajustar rodapé
- [x] ajustar autor (via campo personalizado)
- [x] criar categorias para o menu
- [x] ajustar Google Analytics
- [x] ver padrão do post
- [x] ver tipos de autores para os conteúdos
- [x] melhorar páginas de categorias
- [x] melhorar home
- [x] melhorar experiência mobile
- [x] Rever background compatível com o Divi
- [x] Atualizar página com conteúdo revisado
- [x] Verificar experiência final

## **Critérios de Aceitação**

**Dado que** sou usuário da internet
**Quando** acesso o site do felicilab
**então** tenho uma melhor experiência no site

**Comment by danielgula** [comment]
De acordo com refinamento com @wforte88 , @danielgula e @Clarisse1983 vão refinar a home para terminar de melhorar o site e entregar a versão temporária funcionando.

**Comment by danielgula** [comment]
Foram feitos ajustes para compatibilizar o menu e o background do site para melhor experiência com o Divi. Vamos agendar um refinamento com designlab e publicilab na validação e sugestões de melhoria da versão atual.

**Comment by RaniGub** [comment]
----Verificações da versão Desktop----
Sugestões:
- Testar as opções no topo do site:
1. Assinatura negativa com sem círculo no fundo;
2. Assinatura original com fundo branco (ou outro que gere constraste) e sem círculo no fundo;
3. Integrar assinatura negativa com a frase 'Bem-vinde ao..." como imagem com fundo transparente.

- Acertar background do módulo 'Projetado pela ESP..." no rodapé para o mesmo do background da página sobreposta;
- Dar unidade de cor ao padrão dos links, no módulo de 'saiba mais' está com um azul, no decorrer do texto está com outro tom de azul;
- Experimentar um corpo de texto 'regular' para áreas de conteúdo e com 90% de preto;
- Unificar estilo visual do texto do Blog e Fala, Meu Povo!
- Padronizar destaques nos textos,
- Diminuir espaçamento entre títulos e início do texto;
- Padronizar quebra de texto nas imagens para que não haja linhas viúvas;
- Padronizar cor de destaque em título de 'saiba mais' (em vermelho) e nos títulos que instigam a continuação da leitura de outros conteúdos;
- Verificar o campo de 'próximas postagens' para que quebre a linha do texto e fiquem na mesma altura. Verificar cor de fundo dessa mesma seção. E, se o título é 'Próximas postagens' por que a anterior é mostrada? Talvez 'Postagens' resolva;
- Dar destaque ao 'ler mais' nos módulos do blog e testar alinhamento à direita;
- Modificar o texto 'Entradas antigas' para 'Postagens passadas' ou 'Postagens antigas'. Verificar com a Cla o melhor termo;
- Ao clicar no link da próxima história sobre Mulheres na TI, é aberta uma nova guia. O conteúdo deve ser aberto na guia atual se o conteúdo for interno. O mesmo acontece com outros links;

**Comment by RaniGub** [comment]
- Verificar FavIcon
