### ISSUE TITLE
Criar Página de conteúdos especiais do Capítulo iSUS

### ISSUE THREAD

**Issue by danielgula** [EscolaDeSaudePublica/sus.ce.gov.br#57]
## **Objetivo**

**Como** usuário
**Quero** acessar uma página extra
**Para** ver conteúdos especiais do capítulo iSUS

## **Contexto**

Foi criado o subsite no Wordpress sus.ce.gov.br/isus, mapeando para https://i.sus.ce.gov.br/, local este que receberá conteúdos relacionados ao iSUS. Em uma publicação da escola, um capítulo, escrito pelo Felicilab, deverá chamar diversos links de material extra, como vídeos e conteúdo interativo. O documento já especificou o link desse conteúdo: https://i.sus.ce.gov.br/extra

## **Escopo**

Após essas definições, publicilab + ciencialab farão:

Publicilab + Ciêncialab

- [x] Revisão de conteúdos da página (definir data)
- [x] Ordem de conteúdos da narrativa
- [x] Republicação de conteúdos (não ligando ao Google Drive)

Designlab

- [x] criar página no subsite com o slug 'extra'
- [x] inserir conteúdos do documento compartilhado com os links
- [x] Inserir conteúdos atualizados
- [x] Novo layout (padrão iSUS)
- [x] Criar link "confira as atualizações no site do felicilab" - após inserir projeto do iSUS no site
- [x] Organizar conteúdos e experiência mobile

## **Critérios de Aceitação**

**Dado que** estou lendo o capítulo iSUS
**Quando** clico no link de conteúdo especial
**Então** vejo uma página com os links de material extra

## Observações
Links do doc compartilhado
https://docs.google.com/document/d/19FCUHXYbJdzshyVZpfptsKDG5GxwTUROJz4WCAa5g9Q/edit
Acompanhar construção da linha do tempo:
https://github.com/EscolaDeSaudePublica/sus.ce.gov.br/issues/58

**Comment by ClarisCaval** [comment]
@danielgula a diferença entre essa página e a própria página do iSUS me incomodou bastante. Nem parece que estamos falando do mesmo produto - a proporção das fontes, as cores... Penso que embora seja um link que só será disponibilizado através do livro, devia preservar uma harmonia com o que já existe de conteúdo sobre o produto. Inclusive pq é possível que a gente estimule, após o lançamento do capítulo, o público geral a visitar esses conteúdos. E esse vídeo de 1 ano do FeliciLab não deve estar aí, não vamos divulgá-lo externamente sem algumas mudanças necessárias.

**Comment by danielgula** [comment]
> @danielgula a diferença entre essa página e a própria página do iSUS me incomodou bastante. Nem parece que estamos falando do mesmo produto - a proporção das fontes, as cores... Penso que embora seja um link que só será disponibilizado através do livro, devia preservar uma harmonia com o que já existe de conteúdo sobre o produto. Inclusive pq é possível que a gente estimule, após o lançamento do capítulo, o público geral a visitar esses conteúdos. E esse vídeo de 1 ano do FeliciLab não deve estar aí, não vamos divulgá-lo externamente sem algumas mudanças necessárias.

Clarisse, é possível refinar isso com o time do Ciêncialab? Todos os conteúdos foram solicitados por eles. Sobre o design, o iSUS não tem manual de identidade nenhum. Mas em comum acordo podemos encontrar uma definição para isso.

Apenas por questão de histórico, estamos falando da página https://i.sus.ce.gov.br/extra/

**Comment by danielgula** [comment]
De acordo com nosso último refinamento, ficaram as seguintes atividades a serem feitas:
1. Entrar em contato com Ascom para ver o layout visual da publicação e formatos digitais dele
2. Perguntar para interessados do livro se haverá algum outro conteúdo extra de algum capítulo da publicação

Após essas definições, publicilab + ciencialab farão:
1. revisão de conteúdos da página
2. ordem de conteúdos da narrativa
3. Republicação de conteúdos (não ligando ao Google Drive

Após essas definições, designLab fará:
1. Novo layout (padrão iSUS ou da publicação)
2. Criar menu fixo com links âncora
3. Criar link "confira as atualizações no site do felicilab" - após inserir projeto do iSUS no site
4. Organizar conteúdos e experiência mobile

@wforte88 @Clarisse1983 @geniltonfaheinajr copiados para acompanhamento e providências

**Comment by ClarisCaval** [comment]
Aqui o showcase Todos Juntos, que estava no drive, e que Ana acabou de subir pro canal:
https://www.youtube.com/watch?v=rkPUzvNXlNI

**Comment by danielgula** [comment]
Atualizando a demanda, cujas atividades foram adicionadas ao card:

1. Entrar em contato com Ascom para ver o layout visual da publicação e formatos digitais dele - R. vai demorar e portanto faremos com o layout da página do iSUS
2. Perguntar para interessados do livro se haverá algum outro conteúdo extra de algum capítulo da publicação - R. não teremos outro conteúdo assim, portanto faremos pelo layout da página do iSUS

Após essas definições, publicilab + ciencialab farão:

1. revisão de conteúdos da página
2. ordem de conteúdos da narrativa
3. Republicação de conteúdos (não ligando ao Google Drive)

Atribuições do designlab:

1. Inserir conteúdos atualizados
2. Novo layout (padrão iSUS) - JÁ INICIADO
3. Criar menu fixo com links âncora
4. Criar link "confira as atualizações no site do felicilab" - após inserir projeto do iSUS no site
5. Organizar conteúdos e experiência mobile

@Clarisse1983 e @geniltonfaheinajr quando os conteúdos estarão revisados?

**Comment by geniltonfaheinajr** [comment]
Em junho, a previsão de lançamento do livro seria em agosto. Pedi uma posição da Lígia sobre o lançamento do livo, pois assim que ele for lançado precisaremos da página também lançada.

**Comment by geniltonfaheinajr** [comment]
> Atualizando a demanda, cujas atividades foram adicionadas ao card:
> 
> 1. Entrar em contato com Ascom para ver o layout visual da publicação e formatos digitais dele - R. vai demorar e portanto faremos com o layout da página do iSUS
> 2. Perguntar para interessados do livro se haverá algum outro conteúdo extra de algum capítulo da publicação - R. não teremos outro conteúdo assim, portanto faremos pelo layout da página do iSUS
> 
> Após essas definições, publicilab + ciencialab farão:
> 
> 1. revisão de conteúdos da página
> 2. ordem de conteúdos da narrativa
> 3. Republicação de conteúdos (não ligando ao Google Drive)
> 
> Atribuições do designlab:
> 
> 1. Inserir conteúdos atualizados
> 2. Novo layout (padrão iSUS) - JÁ INICIADO
> 3. Criar menu fixo com links âncora
> 4. Criar link "confira as atualizações no site do felicilab" - após inserir projeto do iSUS no site
> 5. Organizar conteúdos e experiência mobile
> 
> @Clarisse1983 e @geniltonfaheinajr quando os conteúdos estarão revisados?

Resgatando o que decidimos na última reunião sobre essa pauta. Os vídeos a serem apresentados no capítulo seriam divulgados a partir do Youtube e não mais a partir do drive.
No entanto, agora temos essa questão sobre as políticas de comunicação.
Precisamos decidir essas questões para deixar na ponta da agulha quando o livro for lançado.

**Comment by ClarisCaval** [comment]
@danielgula atualizei os textos a serem apresentados na página no doc original tá?
https://docs.google.com/document/d/19FCUHXYbJdzshyVZpfptsKDG5GxwTUROJz4WCAa5g9Q/edit

**Comment by danielgula** [comment]
Página atualizada e aguardando revisão. Segue o novo link:
https://i.sus.ce.gov.br/capitulo-livro-esp/
Apenas o vídeo com os depoimentos é que está o anterior, pois o novo está em revisão também.

**Comment by geniltonfaheinajr** [comment]
> Página atualizada e aguardando revisão. Segue o novo link: https://i.sus.ce.gov.br/capitulo-livro-esp/ Apenas o vídeo com os depoimentos é que está o anterior, pois o novo está em revisão também.

@Clarisse1983 @danielgula acredito que neste caso será necessário fazer um novo alinhamento com a equipe editorial, pois o link divulgado no texto é outro. https://i.sus.ce.gov.br/extra

O caminho mais interessante não seria manter esse mesmo endereço?
![Screenshot_20211229-211158](https://user-images.githubusercontent.com/72393884/147712171-d1765a08-a19d-4cc4-a6ab-93a511780cb5.png)

**Comment by geniltonfaheinajr** [comment]
> Página atualizada e aguardando revisão. Segue o novo link: https://i.sus.ce.gov.br/capitulo-livro-esp/ Apenas o vídeo com os depoimentos é que está o anterior, pois o novo está em revisão também.

E parabéns, Dani!

**Comment by geniltonfaheinajr** [comment]
@danielgula verificar com a ASCOM se é possível alterarmos o link neste momento. Alinhei com @Clarisse1983 e optamos por esse caminho, de inserir o link novo que vc sugeriu.

**Comment by danielgula** [comment]
Passamos a demanda para que a ASCOM possa usar o novo caminho da página.
Colocamos o novo vídeo da experiência de desenvolvimento do iSUS no Youtube e linkamos na página (https://youtu.be/RtqSPtM7pek)
Demanda está concluída e será encerrada.

**Comment by uira** [comment]
@danielgula @ClarisCaval , vamos subir esse vídeo no instagram e no tuiter com a narrativa do Edital,

**Comment by geniltonfaheinajr** [comment]
@danielgula alguma atualização da ASCOM quanto à mudança do link?

**Comment by geniltonfaheinajr** [comment]
@Clarisse1983 lembrei que lááá atrás comentamos da possibilidade de criar um termo de uso de imagem e som para quem forneceu conteúdo. Vc ainda acha que se aplica?

**Comment by ClarisCaval** [comment]
@geniltonfaheinajr acho que se aplica sim. A gente tem o termo padrão, só precisamos enviar para as pessoas que participaram do vídeo. Você consegue recontatá-los e enviar isso?
