### ISSUE TITLE
Criar novo espaço "ESPvirtual" no site Elmo

### ISSUE THREAD

**Issue by marameida** [EscolaDeSaudePublica/sus.ce.gov.br#59]
## **Objetivo**

**Como** usuário do site Elmo
**Quero** visualizar o item "ESPvirtual" 
**Para** estar melhor integrada ao "ambiente virtual de aprendizagem" .

## **Contexto**
Atualmente  quando acessamos o site do Elmo, não existe comunicação com o AVA e seu conteúdo. 

## **Escopo**

- [x] Incluir item "ESPvirtual" no site do Elmo;
- [x] Integrar as informações presentes no AVA com o site do Elmo;
- [x] Permitir acesso das pessoas que realizaram o treinamento ao AVA por meio do site

## **Critérios de Aceitação**

**Dado que**ao acessar o site do Elmo
**Quando**  no item "ESPvirtual" 
**então** podemos  visualizar o AVA e consequentes espaços dos cursos do Elmo.

# Observações
https://www.esp.ce.gov.br/2019/01/14/esp-virtual/

**Comment by marameida** [comment]
Necessário melhor alinhamento desta demanda com Clayton, @wforte88  e @danielgula.

**Comment by marameida** [comment]
Agendada reunião de refinamento com @danielgula, Clayton e @chicaothiago 
Data: 09/06/2021
Horário: 9h

**Comment by marameida** [comment]
Ata breve de reunião 09/06/21: presentes Samara, Clayton, Cleo, Chicão e Daniel.

Discutido como fazer melhor integração entre AVA e site ELMO;
Espaço para acesso ao AVA descrito na aba "TREINAMENTOS" e no MENU de opções do site.
Necessário maior detalhamento sobre os tipos de treinamento (EAD e PRESENCIAL no site), informando sobre as demais ferramentas (iSUS e AVA) que fazem parte do suporte pós-treinamento.

SUGESTÕES DE ENCAMINHAMENTO:

Produção de novos vídeos detalhando o acesso e os tipos de ferramentas de suporte;
Inclusão de mais depoimentos no site, sendo coletados com profissionais que fizeram o treinamento.

**Comment by danielgula** [comment]
Foi inserido um nível se submeno na aba treinamento para acessar o link abaixo fornecido pelo CEDES
http://cursos.espvirtual.esp.ce.gov.br/

**Comment by marameida** [comment]
Ok, @danielgula. Vamos  fechar essa atividade.
