### ISSUE TITLE
Criar artigo "Respostas esperadas de tratamentos com o Elmo"

### ISSUE THREAD

**Issue by wforte88** [EscolaDeSaudePublica/sus.ce.gov.br#6]
Adaptar o conteúdo abaixo para um projeto (post) na categoria "Capacitação":

### Fatores associados a boa resposta de uso do Elmo

**5 a 15 minutos de uso**

- Diminuição da dispneia
- Sensação de maior conforto ao respirar
- Fácies com expressão mais tranquila (reversão de sinais de pânico)
- Diminuição do uso de m. acessória da resp.
- Redução da frequência respiratória
- Redução da frequência cardíaca
- Redução do grau de incursão respiratória
- Melhora da SpO2 para a mesma FiO2 anterior

Obs.: A ausência desses fatores NÃO significa necessidade imediata de intubação, mas exige reavaliação imediata do modo de emprego do Elmo.

**30 min a 2 horas de uso**

- Diminuição da dispneia
- Sensação de maior conforto ao respirar
- Fácies com expressão mais tranquila (reversão de sinais de pânico, sono e desejo de deitar)
- Diminuição do uso de m. acessória da resp.
- Redução da frequência respiratória
- Redução da frequência cardíaca
- Redução do grau de incursão respiratória
- Melhora da SpO2 para a mesma FIO2 anterior
- Gasometria arterial mostrando PaO2/FiO2 com aumento de 30% do valor medido anteriormente e pH e PaCO2 estáveis ou com menor grau de alcalose respiratória, redução do lactato arterial.

**A partir de 6h de uso**

- Diminuição progressiva da dispneia
- Redução progressiva da FIO2 necessária para SpO2 > 92-93%
- Tolerância a longos períodos (>4h) no dispositivo
- Capacidade para conciliar o sono em uso do Elmo
- Desmame gradual da FiO2 e outros parâmetros da terapia intermitente ao ELMO, por exemplo, da FiO2 e fluxos da CNAF ou do fluxo de O2 na máscara de reservatório 
- Gasometria arterial mostrando PaO2/FiO2 progressivamente melhor com pH e PaCO2 estáveis sem piora do lactato arterial

Obs.: A falha deve ser prontamente reconhecida e a conduta quanto a indicação de IOT deve ser tomada pela equipe médica responsável.

**Comment by danielgula** [comment]
Os conteúdos dessa página serão transferidos para a issue abaixo:
https://github.com/EscolaDeSaudePublica/sus.ce.gov.br/issues/19
