### ISSUE TITLE
Enviar imagens de logo do Elmo para integração com iSUS

### ISSUE THREAD

**Issue by marameida** [EscolaDeSaudePublica/sus.ce.gov.br#61]
## **Objetivo**

**Como**  usuária do ISUS
**Quero** acessar a determinadas imagens (descritas em "observações")
**Para**integrar o site Elmo ao aplicativo em questão. .

## **Contexto**
Atualmente a equipe do ISUS está realizando a integração e fez a solicitação.

## **Escopo**

- [x] Solicitar ao designlab (@danielgula ) enviar imagens aqui descritas para a equipe do Elmo (contato @chicaotgv )

## **Critérios de Aceitação**

**Dado que**
**Quando** 
**então** .

# Observações
 
"ESPECIFICAÇÃO DAS IMAGENS"
largura="140"
altura="100"

No formato SVG

Atualmente são como se fossem ícones:
Possuem as cores

plano de fundo: #2DAFE6
icone: #fff

para os cards:
Materiais
Depoimentos
Biblioteca
Doações

**Comment by danielgula** [comment]
Segue exemplos para validação e teste no modelo.

[iSUS.zip](https://github.com/EscolaDeSaudePublica/sus.ce.gov.br/files/6697632/iSUS.zip)

**Comment by oxechicao** [comment]
@danielgula as imagens são um quadrado de fundo transparente :\

**Comment by danielgula** [comment]
Ocorreu um erro na exportação pois os elementos eram imagens em bitmap. Oe elementos foram todos redesenhados em vetor para atender às especificações e agora devem estar em conformidade. Segue arquivo corrigido com os elementos SVG.
[iSUS.zip](https://github.com/EscolaDeSaudePublica/sus.ce.gov.br/files/6709470/iSUS.zip)

**Comment by marameida** [comment]
Ciente. Atividade em progresso.

**Comment by clarissagpeixoto** [comment]
Pessoal, temos imagens com várias extensões e formatos. Caso ajude, segue o link: https://drive.google.com/drive/u/2/folders/1Es586olWp9nGjgIex4IN-akEA4rQv3Uu

**Comment by marameida** [comment]
No aguardo por devolutiva de @oxechicao sobre imagens recebidas.

**Comment by marameida** [comment]
Confirmado recebido das imagens com @oxechicao . Atividade atendida.
