### ISSUE TITLE
Ajustar nome no site do Elmo de "Capacitação" para "Treinamento"

### ISSUE THREAD

**Issue by marameida** [EscolaDeSaudePublica/sus.ce.gov.br#62]
## **Objetivo**

**Como** usuária do site elmo 
**Quero** substituir o item "capacitação" por treinamento
**Para** para o termo ficar mais adequado.

## **Contexto**
Atualmente o termo ainda presente no site está como "capacitação"

## **Escopo**

**Ascom**
 - [x] Revisar página "Faça seu treinamento"

**Designlab**
- [x] Substituir a palavra "capacitação" por "treinamento" no menu
- [x] Substituir o nome da página para "faça seu treinamento"
- [x] Substituir aba do menu para "fazer treinamento"
- [x]  Substituir a palavra "capacitação" por "treinamento" na seção de treinamento na página inicial
- [x] Atualizar a página "Faça seu Treinamento"

## **Critérios de Aceitação**

**Dado que** ao acessar o site
**Quando** visualizar as abas específicas 
**então** o termo referente será de "treinamento" ao invés de "capacitação"

# Observações

Verificar Site:
https://sus.ce.gov.br/elmo/faca-sua-capacitacao/

**Comment by danielgula** [comment]
@marameida, alterei as atividades do card conforme nosso refinamento. Avaliando todo o site, o designlab fez todos os ajustes de conteúdos, menus, elementos e páginas de acesso (veja no card). Fica a cargo da Ascom e responsáveis fazerem a correção do texto da página https://sus.ce.gov.br/elmo/faca-seu-treinamento/ para que possamos atualizar.

**Comment by marameida** [comment]
Ciente @danielgula. Vamos verificar essa última pendência com a ASCOM e CEDES também.
