### ISSUE TITLE
Criar artigo "Contraindicações do Elmo"

### ISSUE THREAD

**Issue by wforte88** [EscolaDeSaudePublica/sus.ce.gov.br#7]
Adaptar o conteúdo abaixo para um projeto (post) na categoria "Capacitação":

## Contraindicações de uso do Elmo

Torpor ou agitação psicomotora, desorientação, incapacidade de cooperar
Glasgow < 8 
Exacerbação de Asma, DPOC, fibrose pulmonar ou outras pneumopatias
Instabilidade hemodinâmica (PAS < 90 mmHg ou PAM < 65 mmHg) ou necessidade de drogas vasoativas
Risco iminente de parada respiratória
Pneumotórax ou pneumomediastino
Acidose respiratória (pH < 7,35 com PaCO2 > 46mmHg) 
Sinais de fadiga muscular respiratória  (respiração paradoxal, uso de m. acessória)
Náuseas ou vômitos
Patologias do canal auditivo
Uso de sondas nasoenteral ou nasogástrica
Claustrofobia

**Comment by danielgula** [comment]
A página será tratada agora como conteúdo da issue:
https://github.com/EscolaDeSaudePublica/sus.ce.gov.br/issues/21
