### ISSUE TITLE
Criar site do FeliciLab

### ISSUE THREAD

**Issue by wforte88** [EscolaDeSaudePublica/sus.ce.gov.br#72]
- [ ] Home page
- [x] O que é
- [x] Quem somos
- [ ] Labs
- [x] Produtos
- [x] Como trabalhamos
- [ ] Contato

Links de apoio:
Elementos editoriais:
https://docs.google.com/document/d/1IGCe-kQh5ZpBSmG_licV1UHkyv0HbsWnd0r_KkWnjno/edit#heading=h.qp7aimt2x7aq

**Comment by danielgula** [comment]
Esse épico se encontra dentro do Zenhub, no board da Central de Informações do SUS e, portanto, será encerrado.
