### ISSUE TITLE
Mudanças para visualização do artefato da Oficina DSP no site do Felicilab

### ISSUE THREAD

**Issue by RaniGub** [EscolaDeSaudePublica/sus.ce.gov.br#84]
## **Objetivo**

**Como** designer  
**Quero** realizar mudanças pontuais de visualização
**Para** otimizar a experiência da pessoa usuária

## **Contexto**

Em reunião com Uirá em 27/09/2021, foram sugeridas algumas definições de visualização para o artefato da Oficina de DSP no site do Felicilab.

## **Novo escopo**
- [x] Suprimir 'Project' das URLs do Felicilab
- [x] Ao entrar no site do Felicilab, a URL mostre sus.ce.gov.br/felicilab ao invés de felicilab.esp.ce.gov.br
- [x] Criar visualização para PDF do artefato da Oficina de forma embedada (Ex.: visualização das boards do Figma).

## Observações
![Captura de Tela 2021-09-27 às 18.30.21.png](https://images.zenhubusercontent.com/6100319d73e73a075fefd717/75d18f6d-84b8-4822-bb82-b464120e74c8)

**Comment by RaniGub** [comment]
@danielgula criei essa issue por demanda do Uirá. Já transferi para o Repo do Sus.ce

**Comment by pauloamoreira** [comment]
@danielgula o @uirá também solicitou que todas as urls para onde apontam todos os links da revista devem apresentar a palavra SUS no endereço da url. além disso, solicitou que já fosse criada uma página para o pdf do artefato impresso, para gerar a url para onde o QrCode das capas apontará. quando o artefato estiver concluído, será disponibilizado nessa página.
