### ISSUE TITLE
Site da Residência - Arquitetura da Informação

### ISSUE THREAD

**Issue by raiannyqz** [EscolaDeSaudePublica/sus.ce.gov.br#89]
## **Objetivo**

**Como** Residentes e possíveis ingressantes a residentes
**Quero** precisam obter informações, ter interação e comunicação
**Para** se relacionar com o programa da residência.

## **Contexto**

- Os residentes precisam de um site para melhorar o relacionamento com o programa da Residência Multiprofissional e este, por sua vez, requer uma melhor visibilidade do seu conteúdo informativo.
- Os possíveis ingressantes precisam obter informações a cerca do programa, dos editais, bem como indicativos e outros assuntos que possa interessar a sua participação.
- Neste sentido, devemos criar um site que possa habilitar essa interação do residente e possíveis ingressantes para com o programa servindo como canal informativo e de comunicação.

## **Escopo**

- [x] Reunião com DIPSA
- [x] Pesquisar Referências de Sites
- [x] Brainstorm (possíveis sessões do site)
- [x] Reunião com DIPSA para aprovação da AI

## **Critérios de Aceitação**

- [x] titulo  
**Dado que** ao abrir o site da residência
**Quando** seja possível obter informações sobre o programa e uma comunicação com este
**então** resultando no engajamento e comunicação do residente.

## Observações
https://www.figma.com/file/sBF9hDgBsIM5IXJHQwrUOS/Arquitetura-da-Informa%C3%A7%C3%A3o
https://www.figma.com/file/fLpsySTOeWNzOiB2Bx97yD/Design-Arquitetura?node-id=0%3A1
https://www.figma.com/proto/VuN7wHJhnW2taJwdgRrhGg/Arquitetura?node-id=38%3A295&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=38%3A295

**Comment by raiannyqz** [comment]
Criar registro do site no domínio: https://sus.ce.gov.br/residenciamedicaesp > @danielgula

**Comment by RaniGub** [comment]
@raiannyqz uma dica, além da Jornada dos Residentes, seria interessante criar a Jornada da pessoa que quer ingressar na Residência.

**Comment by raiannyqz** [comment]
> @raiannyqz uma dica, além da Jornada dos Residentes, seria interessante criar a Jornada da pessoa que quer ingressar na Residência.

Obrigada pela observação, este está como objetivo secundário, no caso, posso acrescentá-lo logo.

**Comment by RaniGub** [comment]
Teste de vínculo com Telegram.

**Comment by raiannyqz** [comment]
Entrei em contato com Diego por email para obter algumas informações pontuais de alguns dos termos por eles usados. Ele ficou dá resposta hoje.

**Comment by raiannyqz** [comment]
Aguardo os comentários e sugestões de @RaniGub, @uira e @danielgula  sobre a Home do Site.

**Comment by raiannyqz** [comment]
Organizando o menu, linkando com as paginas
Paginas funcionando: Home e Novos Cursos

https://www.figma.com/proto/VuN7wHJhnW2taJwdgRrhGg/Arquitetura?node-id=38%3A295&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=38%3A295

**Comment by raiannyqz** [comment]
Alterei o nome do arquivo , novo link 
https://www.figma.com/file/VuN7wHJhnW2taJwdgRrhGg/Design-Arquitetura?node-id=0%3A1

**Comment by raiannyqz** [comment]
Devo agendar reunião com a equipe da residência, diante do material que temos? @uira @RaniGub

**Comment by RaniGub** [comment]
> Devo agendar reunião com a equipe da residência, diante do material que temos? @uira @RaniGub

Considerando que serão os norteadores de navegação da página, com certeza.

**Comment by raiannyqz** [comment]
> > Devo agendar reunião com a equipe da residência, diante do material que temos? @uira @RaniGub
> 
> Considerando que serão os norteadores de navegação da página, com certeza.

@RaniGub @uira ótimo, Diego ficou de marcar a reunião e de dá resposta hoje! Portanto, acrescentei a lista: Reunião com DIPSA para aprovação da AI

**Comment by raiannyqz** [comment]
A Elaboração da primeira proposta de arquitetura está sendo desenvolvida no link:
https://www.figma.com/file/fLpsySTOeWNzOiB2Bx97yD/Design-Arquitetura

**Comment by raiannyqz** [comment]
@RaniGub @uira @danielgula com a https://www.figma.com/file/fLpsySTOeWNzOiB2Bx97yD/Design-Arquitetura?node-id=0%3A1
Posso partir para a próxima issue que será o Protótipo Funcional, e eu continuo no próprio Figma? Criando as outras páginas é isto?

**Comment by RaniGub** [comment]
Olá @raiannyqz bom dia, siga o roteiro que lhe passei.

**Comment by raiannyqz** [comment]
Bom dia, Diego está marcando a reunião para amanhã as 10:00hs @uira @RaniGub @RaniGub @danielgula , vocês irão participar, se sim posso confirmar? 

![photo_2021-10-19_09-58-13](https://user-images.githubusercontent.com/28989404/137914390-965beeff-0486-419c-a158-702989cdc9e4.jpg)

**Comment by RaniGub** [comment]
Olá Raianny, não poderei participar.

Em ter., 19 de out. de 2021 10:03, Raianny Queiroz ***@***.***>
escreveu:
