### ISSUE TITLE
Criar seção de depoimentos

### ISSUE THREAD

**Issue by wforte88** [EscolaDeSaudePublica/sus.ce.gov.br#9]
## **Objetivo**

**Como** usuário
**Quero** ver relatos de profissionais da saúde e de pacientes que utilizaram o Elmo
**Para** ter mais credibilidade no produto

## **Contexto**

Estamos vivendo um momento de pandemia. Por esse motivo, muitas instituições privadas e até pessoas físicas têm demonstrado interesse no Capacete Elmo. Nesse contexto, gostaríamos de abrir um item no menu do site do Elmo para mostrar relatos de pessoas que usaram o equipamento. 

## **Escopo**

**Ascom**
- [x] Analisar narrativa (perfil, nariz de cera, jornalismo literário?)
- [x] Verificar Termo de Uso de Imagem
- [x] Listar pessoas dispostas a dar relatos
- [x] Criar relatos
- [x] Definir subtítulo da página

**Designlab**
- [x] Criar seção dentro da página doações
- [x] Inserir informações
- [x] Verificar experiência mobile

## **Critérios de Aceitação**

**Dado que** acesso o site Elmo
**Quando** clico no link depoimentos
**então** visualizo relatos de usuários do Elmo

**Comment by danielgula** [comment]
Página criada em
https://sus.ce.gov.br/elmo/depoimentos/
